// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: HolidayPresent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HolidayGiftActivityPlayerDataMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId         *int32                       `protobuf:"varint,1,req,name=activityId" json:"activityId,omitempty"`
	TriggerGiftDataMsg []*HolidayTriggerGiftDataMsg `protobuf:"bytes,2,rep,name=triggerGiftDataMsg" json:"triggerGiftDataMsg,omitempty"`
}

func (x *HolidayGiftActivityPlayerDataMsg) Reset() {
	*x = HolidayGiftActivityPlayerDataMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HolidayPresent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HolidayGiftActivityPlayerDataMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolidayGiftActivityPlayerDataMsg) ProtoMessage() {}

func (x *HolidayGiftActivityPlayerDataMsg) ProtoReflect() protoreflect.Message {
	mi := &file_HolidayPresent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolidayGiftActivityPlayerDataMsg.ProtoReflect.Descriptor instead.
func (*HolidayGiftActivityPlayerDataMsg) Descriptor() ([]byte, []int) {
	return file_HolidayPresent_proto_rawDescGZIP(), []int{0}
}

func (x *HolidayGiftActivityPlayerDataMsg) GetActivityId() int32 {
	if x != nil && x.ActivityId != nil {
		return *x.ActivityId
	}
	return 0
}

func (x *HolidayGiftActivityPlayerDataMsg) GetTriggerGiftDataMsg() []*HolidayTriggerGiftDataMsg {
	if x != nil {
		return x.TriggerGiftDataMsg
	}
	return nil
}

type HolidayTriggerGiftDataMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TriggerMallId *int32 `protobuf:"varint,1,opt,name=triggerMallId" json:"triggerMallId,omitempty"`
}

func (x *HolidayTriggerGiftDataMsg) Reset() {
	*x = HolidayTriggerGiftDataMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HolidayPresent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HolidayTriggerGiftDataMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolidayTriggerGiftDataMsg) ProtoMessage() {}

func (x *HolidayTriggerGiftDataMsg) ProtoReflect() protoreflect.Message {
	mi := &file_HolidayPresent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolidayTriggerGiftDataMsg.ProtoReflect.Descriptor instead.
func (*HolidayTriggerGiftDataMsg) Descriptor() ([]byte, []int) {
	return file_HolidayPresent_proto_rawDescGZIP(), []int{1}
}

func (x *HolidayTriggerGiftDataMsg) GetTriggerMallId() int32 {
	if x != nil && x.TriggerMallId != nil {
		return *x.TriggerMallId
	}
	return 0
}

var File_HolidayPresent_proto protoreflect.FileDescriptor

var file_HolidayPresent_proto_rawDesc = []byte{
	0x0a, 0x14, 0x48, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x22, 0xa1, 0x01, 0x0a, 0x20, 0x48,
	0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x47, 0x69, 0x66, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x73, 0x67, 0x12,
	0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12,
	0x5d, 0x0a, 0x12, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x47, 0x69, 0x66, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67,
	0x2e, 0x48, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x47,
	0x69, 0x66, 0x74, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x73, 0x67, 0x52, 0x12, 0x74, 0x72, 0x69, 0x67,
	0x67, 0x65, 0x72, 0x47, 0x69, 0x66, 0x74, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x73, 0x67, 0x22, 0x41,
	0x0a, 0x19, 0x48, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72,
	0x47, 0x69, 0x66, 0x74, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x73, 0x67, 0x12, 0x24, 0x0a, 0x0d, 0x74,
	0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x4d, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0d, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x4d, 0x61, 0x6c, 0x6c, 0x49,
	0x64, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x69, 0x6d, 0x7a, 0x68, 0x6f, 0x6e, 0x67, 0x71, 0x69, 0x2f, 0x78, 0x64, 0x64, 0x71, 0x2d, 0x67,
	0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62,
}

var (
	file_HolidayPresent_proto_rawDescOnce sync.Once
	file_HolidayPresent_proto_rawDescData = file_HolidayPresent_proto_rawDesc
)

func file_HolidayPresent_proto_rawDescGZIP() []byte {
	file_HolidayPresent_proto_rawDescOnce.Do(func() {
		file_HolidayPresent_proto_rawDescData = protoimpl.X.CompressGZIP(file_HolidayPresent_proto_rawDescData)
	})
	return file_HolidayPresent_proto_rawDescData
}

var file_HolidayPresent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_HolidayPresent_proto_goTypes = []any{
	(*HolidayGiftActivityPlayerDataMsg)(nil), // 0: com.yq.msg.CityMsg.HolidayGiftActivityPlayerDataMsg
	(*HolidayTriggerGiftDataMsg)(nil),        // 1: com.yq.msg.CityMsg.HolidayTriggerGiftDataMsg
}
var file_HolidayPresent_proto_depIdxs = []int32{
	1, // 0: com.yq.msg.CityMsg.HolidayGiftActivityPlayerDataMsg.triggerGiftDataMsg:type_name -> com.yq.msg.CityMsg.HolidayTriggerGiftDataMsg
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_HolidayPresent_proto_init() }
func file_HolidayPresent_proto_init() {
	if File_HolidayPresent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_HolidayPresent_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*HolidayGiftActivityPlayerDataMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HolidayPresent_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*HolidayTriggerGiftDataMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_HolidayPresent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_HolidayPresent_proto_goTypes,
		DependencyIndexes: file_HolidayPresent_proto_depIdxs,
		MessageInfos:      file_HolidayPresent_proto_msgTypes,
	}.Build()
	File_HolidayPresent_proto = out.File
	file_HolidayPresent_proto_rawDesc = nil
	file_HolidayPresent_proto_goTypes = nil
	file_HolidayPresent_proto_depIdxs = nil
}
