// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: Mail.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MallParamTypeEnum int32

const (
	MallParamTypeEnum_MallParamTypeEnum_Replace  MallParamTypeEnum = 0
	MallParamTypeEnum_DealEquipmentEnum_ServerId MallParamTypeEnum = 1
)

// Enum value maps for MallParamTypeEnum.
var (
	MallParamTypeEnum_name = map[int32]string{
		0: "MallParamTypeEnum_Replace",
		1: "DealEquipmentEnum_ServerId",
	}
	MallParamTypeEnum_value = map[string]int32{
		"MallParamTypeEnum_Replace":  0,
		"DealEquipmentEnum_ServerId": 1,
	}
)

func (x MallParamTypeEnum) Enum() *MallParamTypeEnum {
	p := new(MallParamTypeEnum)
	*p = x
	return p
}

func (x MallParamTypeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MallParamTypeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_Mail_proto_enumTypes[0].Descriptor()
}

func (MallParamTypeEnum) Type() protoreflect.EnumType {
	return &file_Mail_proto_enumTypes[0]
}

func (x MallParamTypeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MallParamTypeEnum) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MallParamTypeEnum(num)
	return nil
}

// Deprecated: Use MallParamTypeEnum.Descriptor instead.
func (MallParamTypeEnum) EnumDescriptor() ([]byte, []int) {
	return file_Mail_proto_rawDescGZIP(), []int{0}
}

type MailTempMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailUid         *string `protobuf:"bytes,1,req,name=mailUid" json:"mailUid,omitempty"`
	MailType        *int32  `protobuf:"varint,2,req,name=mailType" json:"mailType,omitempty"`
	Title           *string `protobuf:"bytes,3,req,name=title" json:"title,omitempty"`
	Content         *string `protobuf:"bytes,4,req,name=content" json:"content,omitempty"`
	Annexes         *string `protobuf:"bytes,5,req,name=annexes" json:"annexes,omitempty"`
	SendTime        *int64  `protobuf:"varint,6,req,name=sendTime" json:"sendTime,omitempty"`
	SendPlayerId    *int64  `protobuf:"varint,7,req,name=sendPlayerId" json:"sendPlayerId,omitempty"`
	SendNickName    *string `protobuf:"bytes,8,req,name=sendNickName" json:"sendNickName,omitempty"`
	ReceivePlayerId *int64  `protobuf:"varint,9,req,name=receivePlayerId" json:"receivePlayerId,omitempty"`
	IsRead          *bool   `protobuf:"varint,10,req,name=isRead" json:"isRead,omitempty"`
	ReadTime        *int64  `protobuf:"varint,11,req,name=readTime" json:"readTime,omitempty"`
	IsGetReward     *bool   `protobuf:"varint,12,req,name=isGetReward" json:"isGetReward,omitempty"`
	IsNeedAnalysis  *bool   `protobuf:"varint,13,opt,name=isNeedAnalysis" json:"isNeedAnalysis,omitempty"`
	QrCodeUrl       *string `protobuf:"bytes,14,opt,name=qrCodeUrl" json:"qrCodeUrl,omitempty"`
}

func (x *MailTempMsg) Reset() {
	*x = MailTempMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailTempMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailTempMsg) ProtoMessage() {}

func (x *MailTempMsg) ProtoReflect() protoreflect.Message {
	mi := &file_Mail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailTempMsg.ProtoReflect.Descriptor instead.
func (*MailTempMsg) Descriptor() ([]byte, []int) {
	return file_Mail_proto_rawDescGZIP(), []int{0}
}

func (x *MailTempMsg) GetMailUid() string {
	if x != nil && x.MailUid != nil {
		return *x.MailUid
	}
	return ""
}

func (x *MailTempMsg) GetMailType() int32 {
	if x != nil && x.MailType != nil {
		return *x.MailType
	}
	return 0
}

func (x *MailTempMsg) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *MailTempMsg) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *MailTempMsg) GetAnnexes() string {
	if x != nil && x.Annexes != nil {
		return *x.Annexes
	}
	return ""
}

func (x *MailTempMsg) GetSendTime() int64 {
	if x != nil && x.SendTime != nil {
		return *x.SendTime
	}
	return 0
}

func (x *MailTempMsg) GetSendPlayerId() int64 {
	if x != nil && x.SendPlayerId != nil {
		return *x.SendPlayerId
	}
	return 0
}

func (x *MailTempMsg) GetSendNickName() string {
	if x != nil && x.SendNickName != nil {
		return *x.SendNickName
	}
	return ""
}

func (x *MailTempMsg) GetReceivePlayerId() int64 {
	if x != nil && x.ReceivePlayerId != nil {
		return *x.ReceivePlayerId
	}
	return 0
}

func (x *MailTempMsg) GetIsRead() bool {
	if x != nil && x.IsRead != nil {
		return *x.IsRead
	}
	return false
}

func (x *MailTempMsg) GetReadTime() int64 {
	if x != nil && x.ReadTime != nil {
		return *x.ReadTime
	}
	return 0
}

func (x *MailTempMsg) GetIsGetReward() bool {
	if x != nil && x.IsGetReward != nil {
		return *x.IsGetReward
	}
	return false
}

func (x *MailTempMsg) GetIsNeedAnalysis() bool {
	if x != nil && x.IsNeedAnalysis != nil {
		return *x.IsNeedAnalysis
	}
	return false
}

func (x *MailTempMsg) GetQrCodeUrl() string {
	if x != nil && x.QrCodeUrl != nil {
		return *x.QrCodeUrl
	}
	return ""
}

type MailListMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailList []*MailTempMsg `protobuf:"bytes,1,rep,name=mailList" json:"mailList,omitempty"`
}

func (x *MailListMsg) Reset() {
	*x = MailListMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailListMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailListMsg) ProtoMessage() {}

func (x *MailListMsg) ProtoReflect() protoreflect.Message {
	mi := &file_Mail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailListMsg.ProtoReflect.Descriptor instead.
func (*MailListMsg) Descriptor() ([]byte, []int) {
	return file_Mail_proto_rawDescGZIP(), []int{1}
}

func (x *MailListMsg) GetMailList() []*MailTempMsg {
	if x != nil {
		return x.MailList
	}
	return nil
}

type MailListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MailListReq) Reset() {
	*x = MailListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mail_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailListReq) ProtoMessage() {}

func (x *MailListReq) ProtoReflect() protoreflect.Message {
	mi := &file_Mail_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailListReq.ProtoReflect.Descriptor instead.
func (*MailListReq) Descriptor() ([]byte, []int) {
	return file_Mail_proto_rawDescGZIP(), []int{2}
}

type MailReadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailUid *string `protobuf:"bytes,1,req,name=mailUid" json:"mailUid,omitempty"`
}

func (x *MailReadReq) Reset() {
	*x = MailReadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mail_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailReadReq) ProtoMessage() {}

func (x *MailReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_Mail_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailReadReq.ProtoReflect.Descriptor instead.
func (*MailReadReq) Descriptor() ([]byte, []int) {
	return file_Mail_proto_rawDescGZIP(), []int{3}
}

func (x *MailReadReq) GetMailUid() string {
	if x != nil && x.MailUid != nil {
		return *x.MailUid
	}
	return ""
}

type MailReadResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret *int32 `protobuf:"varint,1,req,name=ret" json:"ret,omitempty"`
}

func (x *MailReadResp) Reset() {
	*x = MailReadResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mail_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailReadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailReadResp) ProtoMessage() {}

func (x *MailReadResp) ProtoReflect() protoreflect.Message {
	mi := &file_Mail_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailReadResp.ProtoReflect.Descriptor instead.
func (*MailReadResp) Descriptor() ([]byte, []int) {
	return file_Mail_proto_rawDescGZIP(), []int{4}
}

func (x *MailReadResp) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

type MailGetRewardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailUid *string `protobuf:"bytes,1,req,name=mailUid" json:"mailUid,omitempty"`
}

func (x *MailGetRewardReq) Reset() {
	*x = MailGetRewardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mail_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailGetRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailGetRewardReq) ProtoMessage() {}

func (x *MailGetRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_Mail_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailGetRewardReq.ProtoReflect.Descriptor instead.
func (*MailGetRewardReq) Descriptor() ([]byte, []int) {
	return file_Mail_proto_rawDescGZIP(), []int{5}
}

func (x *MailGetRewardReq) GetMailUid() string {
	if x != nil && x.MailUid != nil {
		return *x.MailUid
	}
	return ""
}

type MailGetRewardResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret      *int32  `protobuf:"varint,1,req,name=ret" json:"ret,omitempty"`
	Reward   *string `protobuf:"bytes,2,opt,name=reward" json:"reward,omitempty"`
	IsExpire *int32  `protobuf:"varint,3,opt,name=isExpire" json:"isExpire,omitempty"`
}

func (x *MailGetRewardResp) Reset() {
	*x = MailGetRewardResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mail_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailGetRewardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailGetRewardResp) ProtoMessage() {}

func (x *MailGetRewardResp) ProtoReflect() protoreflect.Message {
	mi := &file_Mail_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailGetRewardResp.ProtoReflect.Descriptor instead.
func (*MailGetRewardResp) Descriptor() ([]byte, []int) {
	return file_Mail_proto_rawDescGZIP(), []int{6}
}

func (x *MailGetRewardResp) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

func (x *MailGetRewardResp) GetReward() string {
	if x != nil && x.Reward != nil {
		return *x.Reward
	}
	return ""
}

func (x *MailGetRewardResp) GetIsExpire() int32 {
	if x != nil && x.IsExpire != nil {
		return *x.IsExpire
	}
	return 0
}

type MailGetAllRewardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MailGetAllRewardReq) Reset() {
	*x = MailGetAllRewardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mail_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailGetAllRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailGetAllRewardReq) ProtoMessage() {}

func (x *MailGetAllRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_Mail_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailGetAllRewardReq.ProtoReflect.Descriptor instead.
func (*MailGetAllRewardReq) Descriptor() ([]byte, []int) {
	return file_Mail_proto_rawDescGZIP(), []int{7}
}

type MailGetAllRewardResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret      *int32  `protobuf:"varint,1,req,name=ret" json:"ret,omitempty"`
	Reward   *string `protobuf:"bytes,2,opt,name=reward" json:"reward,omitempty"`
	IsExpire *int32  `protobuf:"varint,3,opt,name=isExpire" json:"isExpire,omitempty"`
}

func (x *MailGetAllRewardResp) Reset() {
	*x = MailGetAllRewardResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mail_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailGetAllRewardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailGetAllRewardResp) ProtoMessage() {}

func (x *MailGetAllRewardResp) ProtoReflect() protoreflect.Message {
	mi := &file_Mail_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailGetAllRewardResp.ProtoReflect.Descriptor instead.
func (*MailGetAllRewardResp) Descriptor() ([]byte, []int) {
	return file_Mail_proto_rawDescGZIP(), []int{8}
}

func (x *MailGetAllRewardResp) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

func (x *MailGetAllRewardResp) GetReward() string {
	if x != nil && x.Reward != nil {
		return *x.Reward
	}
	return ""
}

func (x *MailGetAllRewardResp) GetIsExpire() int32 {
	if x != nil && x.IsExpire != nil {
		return *x.IsExpire
	}
	return 0
}

type MailDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailUid *string `protobuf:"bytes,1,req,name=mailUid" json:"mailUid,omitempty"`
}

func (x *MailDeleteReq) Reset() {
	*x = MailDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mail_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailDeleteReq) ProtoMessage() {}

func (x *MailDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_Mail_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailDeleteReq.ProtoReflect.Descriptor instead.
func (*MailDeleteReq) Descriptor() ([]byte, []int) {
	return file_Mail_proto_rawDescGZIP(), []int{9}
}

func (x *MailDeleteReq) GetMailUid() string {
	if x != nil && x.MailUid != nil {
		return *x.MailUid
	}
	return ""
}

type MailDeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret *int32 `protobuf:"varint,1,req,name=ret" json:"ret,omitempty"`
}

func (x *MailDeleteResp) Reset() {
	*x = MailDeleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mail_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailDeleteResp) ProtoMessage() {}

func (x *MailDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_Mail_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailDeleteResp.ProtoReflect.Descriptor instead.
func (*MailDeleteResp) Descriptor() ([]byte, []int) {
	return file_Mail_proto_rawDescGZIP(), []int{10}
}

func (x *MailDeleteResp) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

type MailDeleteAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailType *int32 `protobuf:"varint,1,opt,name=mailType" json:"mailType,omitempty"`
}

func (x *MailDeleteAllReq) Reset() {
	*x = MailDeleteAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mail_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailDeleteAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailDeleteAllReq) ProtoMessage() {}

func (x *MailDeleteAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_Mail_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailDeleteAllReq.ProtoReflect.Descriptor instead.
func (*MailDeleteAllReq) Descriptor() ([]byte, []int) {
	return file_Mail_proto_rawDescGZIP(), []int{11}
}

func (x *MailDeleteAllReq) GetMailType() int32 {
	if x != nil && x.MailType != nil {
		return *x.MailType
	}
	return 0
}

type MailDeleteAllResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret *int32 `protobuf:"varint,1,req,name=ret" json:"ret,omitempty"`
}

func (x *MailDeleteAllResp) Reset() {
	*x = MailDeleteAllResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mail_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailDeleteAllResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailDeleteAllResp) ProtoMessage() {}

func (x *MailDeleteAllResp) ProtoReflect() protoreflect.Message {
	mi := &file_Mail_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailDeleteAllResp.ProtoReflect.Descriptor instead.
func (*MailDeleteAllResp) Descriptor() ([]byte, []int) {
	return file_Mail_proto_rawDescGZIP(), []int{12}
}

func (x *MailDeleteAllResp) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

var File_Mail_proto protoreflect.FileDescriptor

var file_Mail_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x4d, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x63, 0x6f,
	0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67,
	0x22, 0xb7, 0x03, 0x0a, 0x0b, 0x4d, 0x61, 0x69, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x4d, 0x73, 0x67,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x55, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x55, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61,
	0x69, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x61,
	0x69, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6e, 0x6e, 0x65, 0x78, 0x65,
	0x73, 0x18, 0x05, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6e, 0x6e, 0x65, 0x78, 0x65, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x02,
	0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c,
	0x73, 0x65, 0x6e, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x07, 0x20, 0x02,
	0x28, 0x03, 0x52, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x08, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x4e, 0x69, 0x63, 0x6b,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x09, 0x20, 0x02, 0x28, 0x03, 0x52, 0x0f, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x69, 0x73, 0x52, 0x65, 0x61, 0x64, 0x18, 0x0a, 0x20, 0x02, 0x28, 0x08, 0x52, 0x06,
	0x69, 0x73, 0x52, 0x65, 0x61, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x0b, 0x20, 0x02, 0x28, 0x03, 0x52, 0x08, 0x72, 0x65, 0x61, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x18, 0x0c, 0x20, 0x02, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x69, 0x73, 0x4e, 0x65, 0x65, 0x64, 0x41, 0x6e,
	0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x69, 0x73,
	0x4e, 0x65, 0x65, 0x64, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x71, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x71, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x4a, 0x0a, 0x0b, 0x4d, 0x61,
	0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x3b, 0x0a, 0x08, 0x6d, 0x61, 0x69,
	0x6c, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67,
	0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x4d, 0x73, 0x67, 0x52, 0x08, 0x6d, 0x61,
	0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x4d, 0x61, 0x69, 0x6c, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x27, 0x0a, 0x0b, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x61,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x55, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x55, 0x69, 0x64, 0x22, 0x20,
	0x0a, 0x0c, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74,
	0x22, 0x2c, 0x0a, 0x10, 0x4d, 0x61, 0x69, 0x6c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x55, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x55, 0x69, 0x64, 0x22, 0x59,
	0x0a, 0x11, 0x4d, 0x61, 0x69, 0x6c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05,
	0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x69, 0x73, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x69, 0x73, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x4d, 0x61, 0x69,
	0x6c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x22, 0x5c, 0x0a, 0x14, 0x4d, 0x61, 0x69, 0x6c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x73, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x22, 0x29,
	0x0a, 0x0d, 0x4d, 0x61, 0x69, 0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x55, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x55, 0x69, 0x64, 0x22, 0x22, 0x0a, 0x0e, 0x4d, 0x61, 0x69,
	0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x22, 0x2e, 0x0a,
	0x10, 0x4d, 0x61, 0x69, 0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x71, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x69, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x61, 0x69, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x22, 0x25, 0x0a,
	0x11, 0x4d, 0x61, 0x69, 0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52,
	0x03, 0x72, 0x65, 0x74, 0x2a, 0x52, 0x0a, 0x11, 0x4d, 0x61, 0x6c, 0x6c, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x54, 0x79, 0x70, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x1d, 0x0a, 0x19, 0x4d, 0x61, 0x6c,
	0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x5f, 0x52,
	0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x44, 0x65, 0x61, 0x6c,
	0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x75, 0x6d, 0x5f, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x10, 0x01, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6d, 0x7a, 0x68, 0x6f, 0x6e, 0x67, 0x71, 0x69,
	0x2f, 0x78, 0x64, 0x64, 0x71, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x61, 0x6d,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62,
}

var (
	file_Mail_proto_rawDescOnce sync.Once
	file_Mail_proto_rawDescData = file_Mail_proto_rawDesc
)

func file_Mail_proto_rawDescGZIP() []byte {
	file_Mail_proto_rawDescOnce.Do(func() {
		file_Mail_proto_rawDescData = protoimpl.X.CompressGZIP(file_Mail_proto_rawDescData)
	})
	return file_Mail_proto_rawDescData
}

var file_Mail_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Mail_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_Mail_proto_goTypes = []any{
	(MallParamTypeEnum)(0),       // 0: com.yq.msg.CityMsg.MallParamTypeEnum
	(*MailTempMsg)(nil),          // 1: com.yq.msg.CityMsg.MailTempMsg
	(*MailListMsg)(nil),          // 2: com.yq.msg.CityMsg.MailListMsg
	(*MailListReq)(nil),          // 3: com.yq.msg.CityMsg.MailListReq
	(*MailReadReq)(nil),          // 4: com.yq.msg.CityMsg.MailReadReq
	(*MailReadResp)(nil),         // 5: com.yq.msg.CityMsg.MailReadResp
	(*MailGetRewardReq)(nil),     // 6: com.yq.msg.CityMsg.MailGetRewardReq
	(*MailGetRewardResp)(nil),    // 7: com.yq.msg.CityMsg.MailGetRewardResp
	(*MailGetAllRewardReq)(nil),  // 8: com.yq.msg.CityMsg.MailGetAllRewardReq
	(*MailGetAllRewardResp)(nil), // 9: com.yq.msg.CityMsg.MailGetAllRewardResp
	(*MailDeleteReq)(nil),        // 10: com.yq.msg.CityMsg.MailDeleteReq
	(*MailDeleteResp)(nil),       // 11: com.yq.msg.CityMsg.MailDeleteResp
	(*MailDeleteAllReq)(nil),     // 12: com.yq.msg.CityMsg.MailDeleteAllReq
	(*MailDeleteAllResp)(nil),    // 13: com.yq.msg.CityMsg.MailDeleteAllResp
}
var file_Mail_proto_depIdxs = []int32{
	1, // 0: com.yq.msg.CityMsg.MailListMsg.mailList:type_name -> com.yq.msg.CityMsg.MailTempMsg
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Mail_proto_init() }
func file_Mail_proto_init() {
	if File_Mail_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Mail_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MailTempMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mail_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MailListMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mail_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*MailListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mail_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*MailReadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mail_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*MailReadResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mail_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*MailGetRewardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mail_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*MailGetRewardResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mail_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*MailGetAllRewardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mail_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*MailGetAllRewardResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mail_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*MailDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mail_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*MailDeleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mail_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*MailDeleteAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mail_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*MailDeleteAllResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Mail_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Mail_proto_goTypes,
		DependencyIndexes: file_Mail_proto_depIdxs,
		EnumInfos:         file_Mail_proto_enumTypes,
		MessageInfos:      file_Mail_proto_msgTypes,
	}.Build()
	File_Mail_proto = out.File
	file_Mail_proto_rawDesc = nil
	file_Mail_proto_goTypes = nil
	file_Mail_proto_depIdxs = nil
}
