// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: Mall.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MallBuyCountTempMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MallId *int32 `protobuf:"varint,1,req,name=mallId" json:"mallId,omitempty"`
	Count  *int32 `protobuf:"varint,2,req,name=count" json:"count,omitempty"`
}

func (x *MallBuyCountTempMsg) Reset() {
	*x = MallBuyCountTempMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mall_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MallBuyCountTempMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MallBuyCountTempMsg) ProtoMessage() {}

func (x *MallBuyCountTempMsg) ProtoReflect() protoreflect.Message {
	mi := &file_Mall_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MallBuyCountTempMsg.ProtoReflect.Descriptor instead.
func (*MallBuyCountTempMsg) Descriptor() ([]byte, []int) {
	return file_Mall_proto_rawDescGZIP(), []int{0}
}

func (x *MallBuyCountTempMsg) GetMallId() int32 {
	if x != nil && x.MallId != nil {
		return *x.MallId
	}
	return 0
}

func (x *MallBuyCountTempMsg) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

type MallTempMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           *int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name         *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	ShopType     *int32  `protobuf:"varint,3,opt,name=shopType" json:"shopType,omitempty"`
	Reward       *string `protobuf:"bytes,4,opt,name=reward" json:"reward,omitempty"`
	Category     *int32  `protobuf:"varint,5,opt,name=category" json:"category,omitempty"`
	Price        *string `protobuf:"bytes,6,opt,name=price" json:"price,omitempty"`
	OldPrice     *string `protobuf:"bytes,7,opt,name=oldPrice" json:"oldPrice,omitempty"`
	PriceAdd     *int32  `protobuf:"varint,8,opt,name=priceAdd" json:"priceAdd,omitempty"`
	IsDouble     *bool   `protobuf:"varint,9,opt,name=isDouble" json:"isDouble,omitempty"`
	BuyLimitType *int32  `protobuf:"varint,10,opt,name=buyLimitType" json:"buyLimitType,omitempty"`
	BuyLimit     *int32  `protobuf:"varint,11,opt,name=buyLimit" json:"buyLimit,omitempty"`
	Sort         *int32  `protobuf:"varint,12,opt,name=sort" json:"sort,omitempty"`
	Param        *string `protobuf:"bytes,13,opt,name=param" json:"param,omitempty"`
	VipLimit     *int32  `protobuf:"varint,14,opt,name=vipLimit" json:"vipLimit,omitempty"`
	RechargeId   *string `protobuf:"bytes,15,opt,name=rechargeId" json:"rechargeId,omitempty"`
}

func (x *MallTempMsg) Reset() {
	*x = MallTempMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mall_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MallTempMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MallTempMsg) ProtoMessage() {}

func (x *MallTempMsg) ProtoReflect() protoreflect.Message {
	mi := &file_Mall_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MallTempMsg.ProtoReflect.Descriptor instead.
func (*MallTempMsg) Descriptor() ([]byte, []int) {
	return file_Mall_proto_rawDescGZIP(), []int{1}
}

func (x *MallTempMsg) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *MallTempMsg) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *MallTempMsg) GetShopType() int32 {
	if x != nil && x.ShopType != nil {
		return *x.ShopType
	}
	return 0
}

func (x *MallTempMsg) GetReward() string {
	if x != nil && x.Reward != nil {
		return *x.Reward
	}
	return ""
}

func (x *MallTempMsg) GetCategory() int32 {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return 0
}

func (x *MallTempMsg) GetPrice() string {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return ""
}

func (x *MallTempMsg) GetOldPrice() string {
	if x != nil && x.OldPrice != nil {
		return *x.OldPrice
	}
	return ""
}

func (x *MallTempMsg) GetPriceAdd() int32 {
	if x != nil && x.PriceAdd != nil {
		return *x.PriceAdd
	}
	return 0
}

func (x *MallTempMsg) GetIsDouble() bool {
	if x != nil && x.IsDouble != nil {
		return *x.IsDouble
	}
	return false
}

func (x *MallTempMsg) GetBuyLimitType() int32 {
	if x != nil && x.BuyLimitType != nil {
		return *x.BuyLimitType
	}
	return 0
}

func (x *MallTempMsg) GetBuyLimit() int32 {
	if x != nil && x.BuyLimit != nil {
		return *x.BuyLimit
	}
	return 0
}

func (x *MallTempMsg) GetSort() int32 {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return 0
}

func (x *MallTempMsg) GetParam() string {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return ""
}

func (x *MallTempMsg) GetVipLimit() int32 {
	if x != nil && x.VipLimit != nil {
		return *x.VipLimit
	}
	return 0
}

func (x *MallTempMsg) GetRechargeId() string {
	if x != nil && x.RechargeId != nil {
		return *x.RechargeId
	}
	return ""
}

type MallBuyCountListMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MallBuyCountList []*MallBuyCountTempMsg `protobuf:"bytes,1,rep,name=mallBuyCountList" json:"mallBuyCountList,omitempty"`
}

func (x *MallBuyCountListMsg) Reset() {
	*x = MallBuyCountListMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mall_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MallBuyCountListMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MallBuyCountListMsg) ProtoMessage() {}

func (x *MallBuyCountListMsg) ProtoReflect() protoreflect.Message {
	mi := &file_Mall_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MallBuyCountListMsg.ProtoReflect.Descriptor instead.
func (*MallBuyCountListMsg) Descriptor() ([]byte, []int) {
	return file_Mall_proto_rawDescGZIP(), []int{2}
}

func (x *MallBuyCountListMsg) GetMallBuyCountList() []*MallBuyCountTempMsg {
	if x != nil {
		return x.MallBuyCountList
	}
	return nil
}

type BuyGoodsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MallId     *int32 `protobuf:"varint,1,req,name=mallId" json:"mallId,omitempty"`
	Count      *int32 `protobuf:"varint,2,req,name=count" json:"count,omitempty"`
	ActivityId *int32 `protobuf:"varint,3,opt,name=activityId" json:"activityId,omitempty"`
}

func (x *BuyGoodsReq) Reset() {
	*x = BuyGoodsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mall_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyGoodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyGoodsReq) ProtoMessage() {}

func (x *BuyGoodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_Mall_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyGoodsReq.ProtoReflect.Descriptor instead.
func (*BuyGoodsReq) Descriptor() ([]byte, []int) {
	return file_Mall_proto_rawDescGZIP(), []int{3}
}

func (x *BuyGoodsReq) GetMallId() int32 {
	if x != nil && x.MallId != nil {
		return *x.MallId
	}
	return 0
}

func (x *BuyGoodsReq) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *BuyGoodsReq) GetActivityId() int32 {
	if x != nil && x.ActivityId != nil {
		return *x.ActivityId
	}
	return 0
}

type BuyGoodsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    *int32  `protobuf:"varint,1,req,name=ret" json:"ret,omitempty"`
	MallId *int32  `protobuf:"varint,2,opt,name=mallId" json:"mallId,omitempty"`
	Reward *string `protobuf:"bytes,3,opt,name=reward" json:"reward,omitempty"`
}

func (x *BuyGoodsResp) Reset() {
	*x = BuyGoodsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mall_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyGoodsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyGoodsResp) ProtoMessage() {}

func (x *BuyGoodsResp) ProtoReflect() protoreflect.Message {
	mi := &file_Mall_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyGoodsResp.ProtoReflect.Descriptor instead.
func (*BuyGoodsResp) Descriptor() ([]byte, []int) {
	return file_Mall_proto_rawDescGZIP(), []int{4}
}

func (x *BuyGoodsResp) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

func (x *BuyGoodsResp) GetMallId() int32 {
	if x != nil && x.MallId != nil {
		return *x.MallId
	}
	return 0
}

func (x *BuyGoodsResp) GetReward() string {
	if x != nil && x.Reward != nil {
		return *x.Reward
	}
	return ""
}

type MallRandomGoodsReqMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopType *int32 `protobuf:"varint,1,req,name=shopType" json:"shopType,omitempty"`
}

func (x *MallRandomGoodsReqMsg) Reset() {
	*x = MallRandomGoodsReqMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mall_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MallRandomGoodsReqMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MallRandomGoodsReqMsg) ProtoMessage() {}

func (x *MallRandomGoodsReqMsg) ProtoReflect() protoreflect.Message {
	mi := &file_Mall_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MallRandomGoodsReqMsg.ProtoReflect.Descriptor instead.
func (*MallRandomGoodsReqMsg) Descriptor() ([]byte, []int) {
	return file_Mall_proto_rawDescGZIP(), []int{5}
}

func (x *MallRandomGoodsReqMsg) GetShopType() int32 {
	if x != nil && x.ShopType != nil {
		return *x.ShopType
	}
	return 0
}

type MallRandomGoodsRespMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret       *int32         `protobuf:"varint,1,req,name=ret" json:"ret,omitempty"`
	MallGoods []*MallTempMsg `protobuf:"bytes,2,rep,name=mallGoods" json:"mallGoods,omitempty"`
}

func (x *MallRandomGoodsRespMsg) Reset() {
	*x = MallRandomGoodsRespMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mall_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MallRandomGoodsRespMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MallRandomGoodsRespMsg) ProtoMessage() {}

func (x *MallRandomGoodsRespMsg) ProtoReflect() protoreflect.Message {
	mi := &file_Mall_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MallRandomGoodsRespMsg.ProtoReflect.Descriptor instead.
func (*MallRandomGoodsRespMsg) Descriptor() ([]byte, []int) {
	return file_Mall_proto_rawDescGZIP(), []int{6}
}

func (x *MallRandomGoodsRespMsg) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

func (x *MallRandomGoodsRespMsg) GetMallGoods() []*MallTempMsg {
	if x != nil {
		return x.MallGoods
	}
	return nil
}

var File_Mall_proto protoreflect.FileDescriptor

var file_Mall_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x4d, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x63, 0x6f,
	0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67,
	0x22, 0x43, 0x0a, 0x13, 0x4d, 0x61, 0x6c, 0x6c, 0x42, 0x75, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x54, 0x65, 0x6d, 0x70, 0x4d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x6c, 0x6c, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x91, 0x03, 0x0a, 0x0b, 0x4d, 0x61, 0x6c, 0x6c, 0x54, 0x65,
	0x6d, 0x70, 0x4d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68, 0x6f,
	0x70, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x68, 0x6f,
	0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x6f, 0x6c, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6f, 0x6c, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x41, 0x64, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x41, 0x64, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x44, 0x6f, 0x75,
	0x62, 0x6c, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x44, 0x6f, 0x75,
	0x62, 0x6c, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x62, 0x75, 0x79, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x62, 0x75, 0x79, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x75, 0x79, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x62, 0x75, 0x79, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x1a, 0x0a,
	0x08, 0x76, 0x69, 0x70, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x76, 0x69, 0x70, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x63,
	0x68, 0x61, 0x72, 0x67, 0x65, 0x49, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72,
	0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x49, 0x64, 0x22, 0x6a, 0x0a, 0x13, 0x4d, 0x61, 0x6c,
	0x6c, 0x42, 0x75, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x73, 0x67,
	0x12, 0x53, 0x0a, 0x10, 0x6d, 0x61, 0x6c, 0x6c, 0x42, 0x75, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x79, 0x71, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x2e,
	0x4d, 0x61, 0x6c, 0x6c, 0x42, 0x75, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x65, 0x6d, 0x70,
	0x4d, 0x73, 0x67, 0x52, 0x10, 0x6d, 0x61, 0x6c, 0x6c, 0x42, 0x75, 0x79, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x5b, 0x0a, 0x0b, 0x42, 0x75, 0x79, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x49, 0x64, 0x22, 0x50, 0x0a, 0x0c, 0x42, 0x75, 0x79, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52,
	0x03, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x22, 0x33, 0x0a, 0x15, 0x4d, 0x61, 0x6c, 0x6c, 0x52, 0x61, 0x6e, 0x64,
	0x6f, 0x6d, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x4d, 0x73, 0x67, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x68, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52,
	0x08, 0x73, 0x68, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x22, 0x69, 0x0a, 0x16, 0x4d, 0x61, 0x6c,
	0x6c, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05,
	0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x3d, 0x0a, 0x09, 0x6d, 0x61, 0x6c, 0x6c, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x79,
	0x71, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x2e, 0x4d, 0x61,
	0x6c, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x4d, 0x73, 0x67, 0x52, 0x09, 0x6d, 0x61, 0x6c, 0x6c, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x69, 0x6d, 0x7a, 0x68, 0x6f, 0x6e, 0x67, 0x71, 0x69, 0x2f, 0x78, 0x64, 0x64,
	0x71, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62,
}

var (
	file_Mall_proto_rawDescOnce sync.Once
	file_Mall_proto_rawDescData = file_Mall_proto_rawDesc
)

func file_Mall_proto_rawDescGZIP() []byte {
	file_Mall_proto_rawDescOnce.Do(func() {
		file_Mall_proto_rawDescData = protoimpl.X.CompressGZIP(file_Mall_proto_rawDescData)
	})
	return file_Mall_proto_rawDescData
}

var file_Mall_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_Mall_proto_goTypes = []any{
	(*MallBuyCountTempMsg)(nil),    // 0: com.yq.msg.CityMsg.MallBuyCountTempMsg
	(*MallTempMsg)(nil),            // 1: com.yq.msg.CityMsg.MallTempMsg
	(*MallBuyCountListMsg)(nil),    // 2: com.yq.msg.CityMsg.MallBuyCountListMsg
	(*BuyGoodsReq)(nil),            // 3: com.yq.msg.CityMsg.BuyGoodsReq
	(*BuyGoodsResp)(nil),           // 4: com.yq.msg.CityMsg.BuyGoodsResp
	(*MallRandomGoodsReqMsg)(nil),  // 5: com.yq.msg.CityMsg.MallRandomGoodsReqMsg
	(*MallRandomGoodsRespMsg)(nil), // 6: com.yq.msg.CityMsg.MallRandomGoodsRespMsg
}
var file_Mall_proto_depIdxs = []int32{
	0, // 0: com.yq.msg.CityMsg.MallBuyCountListMsg.mallBuyCountList:type_name -> com.yq.msg.CityMsg.MallBuyCountTempMsg
	1, // 1: com.yq.msg.CityMsg.MallRandomGoodsRespMsg.mallGoods:type_name -> com.yq.msg.CityMsg.MallTempMsg
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Mall_proto_init() }
func file_Mall_proto_init() {
	if File_Mall_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Mall_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MallBuyCountTempMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mall_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MallTempMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mall_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*MallBuyCountListMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mall_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*BuyGoodsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mall_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*BuyGoodsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mall_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*MallRandomGoodsReqMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mall_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*MallRandomGoodsRespMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Mall_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Mall_proto_goTypes,
		DependencyIndexes: file_Mall_proto_depIdxs,
		MessageInfos:      file_Mall_proto_msgTypes,
	}.Build()
	File_Mall_proto = out.File
	file_Mall_proto_rawDesc = nil
	file_Mall_proto_goTypes = nil
	file_Mall_proto_depIdxs = nil
}
