// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: PupilRankActivity.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PupilRankPb int32

const (
	PupilRankPb_S_PUPIL_RANK_ENTER               PupilRankPb = 213801
	PupilRankPb_S_PUPIL_RANK_GET_INCREASE_RECORD PupilRankPb = 213802
	PupilRankPb_S_PUPIL_RANK_DETAIL              PupilRankPb = 213803
)

// Enum value maps for PupilRankPb.
var (
	PupilRankPb_name = map[int32]string{
		213801: "S_PUPIL_RANK_ENTER",
		213802: "S_PUPIL_RANK_GET_INCREASE_RECORD",
		213803: "S_PUPIL_RANK_DETAIL",
	}
	PupilRankPb_value = map[string]int32{
		"S_PUPIL_RANK_ENTER":               213801,
		"S_PUPIL_RANK_GET_INCREASE_RECORD": 213802,
		"S_PUPIL_RANK_DETAIL":              213803,
	}
)

func (x PupilRankPb) Enum() *PupilRankPb {
	p := new(PupilRankPb)
	*p = x
	return p
}

func (x PupilRankPb) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PupilRankPb) Descriptor() protoreflect.EnumDescriptor {
	return file_PupilRankActivity_proto_enumTypes[0].Descriptor()
}

func (PupilRankPb) Type() protoreflect.EnumType {
	return &file_PupilRankActivity_proto_enumTypes[0]
}

func (x PupilRankPb) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PupilRankPb) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PupilRankPb(num)
	return nil
}

// Deprecated: Use PupilRankPb.Descriptor instead.
func (PupilRankPb) EnumDescriptor() ([]byte, []int) {
	return file_PupilRankActivity_proto_rawDescGZIP(), []int{0}
}

type EnterPupilRankActivityReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId *int32 `protobuf:"varint,1,req,name=activityId" json:"activityId,omitempty"`
}

func (x *EnterPupilRankActivityReq) Reset() {
	*x = EnterPupilRankActivityReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PupilRankActivity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterPupilRankActivityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterPupilRankActivityReq) ProtoMessage() {}

func (x *EnterPupilRankActivityReq) ProtoReflect() protoreflect.Message {
	mi := &file_PupilRankActivity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterPupilRankActivityReq.ProtoReflect.Descriptor instead.
func (*EnterPupilRankActivityReq) Descriptor() ([]byte, []int) {
	return file_PupilRankActivity_proto_rawDescGZIP(), []int{0}
}

func (x *EnterPupilRankActivityReq) GetActivityId() int32 {
	if x != nil && x.ActivityId != nil {
		return *x.ActivityId
	}
	return 0
}

type EnterPupilRankActivityResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret      *int32               `protobuf:"varint,1,req,name=ret" json:"ret,omitempty"`
	RankList []*PupilRankRankData `protobuf:"bytes,2,rep,name=rankList" json:"rankList,omitempty"`
	MyRank   *int32               `protobuf:"varint,3,opt,name=myRank" json:"myRank,omitempty"`
	MyValue  *int32               `protobuf:"varint,4,opt,name=myValue" json:"myValue,omitempty"`
}

func (x *EnterPupilRankActivityResp) Reset() {
	*x = EnterPupilRankActivityResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PupilRankActivity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterPupilRankActivityResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterPupilRankActivityResp) ProtoMessage() {}

func (x *EnterPupilRankActivityResp) ProtoReflect() protoreflect.Message {
	mi := &file_PupilRankActivity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterPupilRankActivityResp.ProtoReflect.Descriptor instead.
func (*EnterPupilRankActivityResp) Descriptor() ([]byte, []int) {
	return file_PupilRankActivity_proto_rawDescGZIP(), []int{1}
}

func (x *EnterPupilRankActivityResp) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

func (x *EnterPupilRankActivityResp) GetRankList() []*PupilRankRankData {
	if x != nil {
		return x.RankList
	}
	return nil
}

func (x *EnterPupilRankActivityResp) GetMyRank() int32 {
	if x != nil && x.MyRank != nil {
		return *x.MyRank
	}
	return 0
}

func (x *EnterPupilRankActivityResp) GetMyValue() int32 {
	if x != nil && x.MyValue != nil {
		return *x.MyValue
	}
	return 0
}

type GetIncreaseRecordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId *int32 `protobuf:"varint,1,req,name=activityId" json:"activityId,omitempty"`
	PlayerId   *int64 `protobuf:"varint,2,req,name=playerId" json:"playerId,omitempty"`
}

func (x *GetIncreaseRecordReq) Reset() {
	*x = GetIncreaseRecordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PupilRankActivity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIncreaseRecordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIncreaseRecordReq) ProtoMessage() {}

func (x *GetIncreaseRecordReq) ProtoReflect() protoreflect.Message {
	mi := &file_PupilRankActivity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIncreaseRecordReq.ProtoReflect.Descriptor instead.
func (*GetIncreaseRecordReq) Descriptor() ([]byte, []int) {
	return file_PupilRankActivity_proto_rawDescGZIP(), []int{2}
}

func (x *GetIncreaseRecordReq) GetActivityId() int32 {
	if x != nil && x.ActivityId != nil {
		return *x.ActivityId
	}
	return 0
}

func (x *GetIncreaseRecordReq) GetPlayerId() int64 {
	if x != nil && x.PlayerId != nil {
		return *x.PlayerId
	}
	return 0
}

type GetIncreaseRecordResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret        *int32                     `protobuf:"varint,1,req,name=ret" json:"ret,omitempty"`
	RecordList []*PupilIncreaseRecordData `protobuf:"bytes,2,rep,name=recordList" json:"recordList,omitempty"`
}

func (x *GetIncreaseRecordResp) Reset() {
	*x = GetIncreaseRecordResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PupilRankActivity_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIncreaseRecordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIncreaseRecordResp) ProtoMessage() {}

func (x *GetIncreaseRecordResp) ProtoReflect() protoreflect.Message {
	mi := &file_PupilRankActivity_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIncreaseRecordResp.ProtoReflect.Descriptor instead.
func (*GetIncreaseRecordResp) Descriptor() ([]byte, []int) {
	return file_PupilRankActivity_proto_rawDescGZIP(), []int{3}
}

func (x *GetIncreaseRecordResp) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

func (x *GetIncreaseRecordResp) GetRecordList() []*PupilIncreaseRecordData {
	if x != nil {
		return x.RecordList
	}
	return nil
}

// *宗门冲榜排行榜数据
type PupilRankRankListMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RankList []*PupilRankRankData `protobuf:"bytes,1,rep,name=rankList" json:"rankList,omitempty"`
}

func (x *PupilRankRankListMsg) Reset() {
	*x = PupilRankRankListMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PupilRankActivity_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PupilRankRankListMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PupilRankRankListMsg) ProtoMessage() {}

func (x *PupilRankRankListMsg) ProtoReflect() protoreflect.Message {
	mi := &file_PupilRankActivity_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PupilRankRankListMsg.ProtoReflect.Descriptor instead.
func (*PupilRankRankListMsg) Descriptor() ([]byte, []int) {
	return file_PupilRankActivity_proto_rawDescGZIP(), []int{4}
}

func (x *PupilRankRankListMsg) GetRankList() []*PupilRankRankData {
	if x != nil {
		return x.RankList
	}
	return nil
}

// *宗门冲榜排行榜数据
type PupilRankRankData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerImageData *PlayerCharacterImageMsg `protobuf:"bytes,1,opt,name=playerImageData" json:"playerImageData,omitempty"`
	Rank            *int32                   `protobuf:"varint,2,opt,name=rank" json:"rank,omitempty"`
	Value           *int32                   `protobuf:"varint,3,opt,name=value" json:"value,omitempty"`
	PupilSectLv     *int32                   `protobuf:"varint,4,opt,name=pupilSectLv" json:"pupilSectLv,omitempty"`
	PupilDataList   []*PupilDataMsg          `protobuf:"bytes,5,rep,name=pupilDataList" json:"pupilDataList,omitempty"`
}

func (x *PupilRankRankData) Reset() {
	*x = PupilRankRankData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PupilRankActivity_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PupilRankRankData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PupilRankRankData) ProtoMessage() {}

func (x *PupilRankRankData) ProtoReflect() protoreflect.Message {
	mi := &file_PupilRankActivity_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PupilRankRankData.ProtoReflect.Descriptor instead.
func (*PupilRankRankData) Descriptor() ([]byte, []int) {
	return file_PupilRankActivity_proto_rawDescGZIP(), []int{5}
}

func (x *PupilRankRankData) GetPlayerImageData() *PlayerCharacterImageMsg {
	if x != nil {
		return x.PlayerImageData
	}
	return nil
}

func (x *PupilRankRankData) GetRank() int32 {
	if x != nil && x.Rank != nil {
		return *x.Rank
	}
	return 0
}

func (x *PupilRankRankData) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *PupilRankRankData) GetPupilSectLv() int32 {
	if x != nil && x.PupilSectLv != nil {
		return *x.PupilSectLv
	}
	return 0
}

func (x *PupilRankRankData) GetPupilDataList() []*PupilDataMsg {
	if x != nil {
		return x.PupilDataList
	}
	return nil
}

// *涨幅数据
type PupilIncreaseRecordData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time    *int64            `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	Type    *int32            `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	AttData *AttributeDataMsg `protobuf:"bytes,3,opt,name=attData" json:"attData,omitempty"`
}

func (x *PupilIncreaseRecordData) Reset() {
	*x = PupilIncreaseRecordData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PupilRankActivity_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PupilIncreaseRecordData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PupilIncreaseRecordData) ProtoMessage() {}

func (x *PupilIncreaseRecordData) ProtoReflect() protoreflect.Message {
	mi := &file_PupilRankActivity_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PupilIncreaseRecordData.ProtoReflect.Descriptor instead.
func (*PupilIncreaseRecordData) Descriptor() ([]byte, []int) {
	return file_PupilRankActivity_proto_rawDescGZIP(), []int{6}
}

func (x *PupilIncreaseRecordData) GetTime() int64 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

func (x *PupilIncreaseRecordData) GetType() int32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *PupilIncreaseRecordData) GetAttData() *AttributeDataMsg {
	if x != nil {
		return x.AttData
	}
	return nil
}

type PupilRankDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId *int32 `protobuf:"varint,1,req,name=activityId" json:"activityId,omitempty"`
	TargetId   *int64 `protobuf:"varint,2,req,name=targetId" json:"targetId,omitempty"`
}

func (x *PupilRankDetailReq) Reset() {
	*x = PupilRankDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PupilRankActivity_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PupilRankDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PupilRankDetailReq) ProtoMessage() {}

func (x *PupilRankDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_PupilRankActivity_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PupilRankDetailReq.ProtoReflect.Descriptor instead.
func (*PupilRankDetailReq) Descriptor() ([]byte, []int) {
	return file_PupilRankActivity_proto_rawDescGZIP(), []int{7}
}

func (x *PupilRankDetailReq) GetActivityId() int32 {
	if x != nil && x.ActivityId != nil {
		return *x.ActivityId
	}
	return 0
}

func (x *PupilRankDetailReq) GetTargetId() int64 {
	if x != nil && x.TargetId != nil {
		return *x.TargetId
	}
	return 0
}

type PupilRankDetailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret      *int32                 `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	TargetId *int64                 `protobuf:"varint,2,opt,name=targetId" json:"targetId,omitempty"`
	TotalMsg []*PupilUpdateTotalMsg `protobuf:"bytes,3,rep,name=totalMsg" json:"totalMsg,omitempty"`
}

func (x *PupilRankDetailResp) Reset() {
	*x = PupilRankDetailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PupilRankActivity_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PupilRankDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PupilRankDetailResp) ProtoMessage() {}

func (x *PupilRankDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_PupilRankActivity_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PupilRankDetailResp.ProtoReflect.Descriptor instead.
func (*PupilRankDetailResp) Descriptor() ([]byte, []int) {
	return file_PupilRankActivity_proto_rawDescGZIP(), []int{8}
}

func (x *PupilRankDetailResp) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

func (x *PupilRankDetailResp) GetTargetId() int64 {
	if x != nil && x.TargetId != nil {
		return *x.TargetId
	}
	return 0
}

func (x *PupilRankDetailResp) GetTotalMsg() []*PupilUpdateTotalMsg {
	if x != nil {
		return x.TotalMsg
	}
	return nil
}

type PupilUpdateTotalMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Graduation  *bool  `protobuf:"varint,1,req,name=graduation" json:"graduation,omitempty"`
	Count       *int32 `protobuf:"varint,2,req,name=count" json:"count,omitempty"`
	UpdateValue *int64 `protobuf:"varint,3,req,name=updateValue" json:"updateValue,omitempty"`
}

func (x *PupilUpdateTotalMsg) Reset() {
	*x = PupilUpdateTotalMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PupilRankActivity_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PupilUpdateTotalMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PupilUpdateTotalMsg) ProtoMessage() {}

func (x *PupilUpdateTotalMsg) ProtoReflect() protoreflect.Message {
	mi := &file_PupilRankActivity_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PupilUpdateTotalMsg.ProtoReflect.Descriptor instead.
func (*PupilUpdateTotalMsg) Descriptor() ([]byte, []int) {
	return file_PupilRankActivity_proto_rawDescGZIP(), []int{9}
}

func (x *PupilUpdateTotalMsg) GetGraduation() bool {
	if x != nil && x.Graduation != nil {
		return *x.Graduation
	}
	return false
}

func (x *PupilUpdateTotalMsg) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *PupilUpdateTotalMsg) GetUpdateValue() int64 {
	if x != nil && x.UpdateValue != nil {
		return *x.UpdateValue
	}
	return 0
}

var File_PupilRankActivity_proto protoreflect.FileDescriptor

var file_PupilRankActivity_proto_rawDesc = []byte{
	0x0a, 0x17, 0x50, 0x75, 0x70, 0x69, 0x6c, 0x52, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x79,
	0x71, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x1a, 0x0c, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x50, 0x75, 0x70,
	0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x57, 0x61, 0x74, 0x63, 0x68, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x19, 0x45,
	0x6e, 0x74, 0x65, 0x72, 0x50, 0x75, 0x70, 0x69, 0x6c, 0x52, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x22, 0xa3, 0x01, 0x0a, 0x1a, 0x45, 0x6e, 0x74,
	0x65, 0x72, 0x50, 0x75, 0x70, 0x69, 0x6c, 0x52, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x41, 0x0a, 0x08, 0x72, 0x61, 0x6e,
	0x6b, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67,
	0x2e, 0x50, 0x75, 0x70, 0x69, 0x6c, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x61, 0x6e, 0x6b, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x08, 0x72, 0x61, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6d, 0x79, 0x52, 0x61, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x79,
	0x52, 0x61, 0x6e, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x52,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x03, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x76, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x4b, 0x0a,
	0x0a, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x2b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43,
	0x69, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x2e, 0x50, 0x75, 0x70, 0x69, 0x6c, 0x49, 0x6e, 0x63, 0x72,
	0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x59, 0x0a, 0x14, 0x50, 0x75,
	0x70, 0x69, 0x6c, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x61, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x4d,
	0x73, 0x67, 0x12, 0x41, 0x0a, 0x08, 0x72, 0x61, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x2e, 0x50, 0x75, 0x70, 0x69, 0x6c, 0x52,
	0x61, 0x6e, 0x6b, 0x52, 0x61, 0x6e, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x72, 0x61, 0x6e,
	0x6b, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xfe, 0x01, 0x0a, 0x11, 0x50, 0x75, 0x70, 0x69, 0x6c, 0x52,
	0x61, 0x6e, 0x6b, 0x52, 0x61, 0x6e, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x55, 0x0a, 0x0f, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4d, 0x73,
	0x67, 0x52, 0x0f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x70, 0x75, 0x70, 0x69, 0x6c, 0x53, 0x65, 0x63, 0x74, 0x4c, 0x76, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x70, 0x75, 0x70, 0x69, 0x6c, 0x53, 0x65, 0x63, 0x74, 0x4c, 0x76, 0x12, 0x46,
	0x0a, 0x0d, 0x70, 0x75, 0x70, 0x69, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x2e, 0x50, 0x75, 0x70, 0x69, 0x6c,
	0x44, 0x61, 0x74, 0x61, 0x4d, 0x73, 0x67, 0x52, 0x0d, 0x70, 0x75, 0x70, 0x69, 0x6c, 0x44, 0x61,
	0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x81, 0x01, 0x0a, 0x17, 0x50, 0x75, 0x70, 0x69, 0x6c,
	0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x3e, 0x0a, 0x07, 0x61, 0x74,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67,
	0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x73,
	0x67, 0x52, 0x07, 0x61, 0x74, 0x74, 0x44, 0x61, 0x74, 0x61, 0x22, 0x50, 0x0a, 0x12, 0x50, 0x75,
	0x70, 0x69, 0x6c, 0x52, 0x61, 0x6e, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71,
	0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x03, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x22, 0x88, 0x01, 0x0a,
	0x13, 0x50, 0x75, 0x70, 0x69, 0x6c, 0x52, 0x61, 0x6e, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x49, 0x64, 0x12, 0x43, 0x0a, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x73, 0x67, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x2e, 0x50, 0x75, 0x70, 0x69, 0x6c, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x73, 0x67, 0x52, 0x08, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x73, 0x67, 0x22, 0x6d, 0x0a, 0x13, 0x50, 0x75, 0x70, 0x69, 0x6c,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x73, 0x67, 0x12, 0x1e,
	0x0a, 0x0a, 0x67, 0x72, 0x61, 0x64, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x08, 0x52, 0x0a, 0x67, 0x72, 0x61, 0x64, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x03, 0x52, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2a, 0x6a, 0x0a, 0x0b, 0x50, 0x75, 0x70, 0x69, 0x6c, 0x52,
	0x61, 0x6e, 0x6b, 0x50, 0x62, 0x12, 0x18, 0x0a, 0x12, 0x53, 0x5f, 0x50, 0x55, 0x50, 0x49, 0x4c,
	0x5f, 0x52, 0x41, 0x4e, 0x4b, 0x5f, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x10, 0xa9, 0x86, 0x0d, 0x12,
	0x26, 0x0a, 0x20, 0x53, 0x5f, 0x50, 0x55, 0x50, 0x49, 0x4c, 0x5f, 0x52, 0x41, 0x4e, 0x4b, 0x5f,
	0x47, 0x45, 0x54, 0x5f, 0x49, 0x4e, 0x43, 0x52, 0x45, 0x41, 0x53, 0x45, 0x5f, 0x52, 0x45, 0x43,
	0x4f, 0x52, 0x44, 0x10, 0xaa, 0x86, 0x0d, 0x12, 0x19, 0x0a, 0x13, 0x53, 0x5f, 0x50, 0x55, 0x50,
	0x49, 0x4c, 0x5f, 0x52, 0x41, 0x4e, 0x4b, 0x5f, 0x44, 0x45, 0x54, 0x41, 0x49, 0x4c, 0x10, 0xab,
	0x86, 0x0d, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x69, 0x6d, 0x7a, 0x68, 0x6f, 0x6e, 0x67, 0x71, 0x69, 0x2f, 0x78, 0x64, 0x64, 0x71, 0x2d,
	0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62,
}

var (
	file_PupilRankActivity_proto_rawDescOnce sync.Once
	file_PupilRankActivity_proto_rawDescData = file_PupilRankActivity_proto_rawDesc
)

func file_PupilRankActivity_proto_rawDescGZIP() []byte {
	file_PupilRankActivity_proto_rawDescOnce.Do(func() {
		file_PupilRankActivity_proto_rawDescData = protoimpl.X.CompressGZIP(file_PupilRankActivity_proto_rawDescData)
	})
	return file_PupilRankActivity_proto_rawDescData
}

var file_PupilRankActivity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_PupilRankActivity_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_PupilRankActivity_proto_goTypes = []any{
	(PupilRankPb)(0),                   // 0: com.yq.msg.CityMsg.PupilRankPb
	(*EnterPupilRankActivityReq)(nil),  // 1: com.yq.msg.CityMsg.EnterPupilRankActivityReq
	(*EnterPupilRankActivityResp)(nil), // 2: com.yq.msg.CityMsg.EnterPupilRankActivityResp
	(*GetIncreaseRecordReq)(nil),       // 3: com.yq.msg.CityMsg.GetIncreaseRecordReq
	(*GetIncreaseRecordResp)(nil),      // 4: com.yq.msg.CityMsg.GetIncreaseRecordResp
	(*PupilRankRankListMsg)(nil),       // 5: com.yq.msg.CityMsg.PupilRankRankListMsg
	(*PupilRankRankData)(nil),          // 6: com.yq.msg.CityMsg.PupilRankRankData
	(*PupilIncreaseRecordData)(nil),    // 7: com.yq.msg.CityMsg.PupilIncreaseRecordData
	(*PupilRankDetailReq)(nil),         // 8: com.yq.msg.CityMsg.PupilRankDetailReq
	(*PupilRankDetailResp)(nil),        // 9: com.yq.msg.CityMsg.PupilRankDetailResp
	(*PupilUpdateTotalMsg)(nil),        // 10: com.yq.msg.CityMsg.PupilUpdateTotalMsg
	(*PlayerCharacterImageMsg)(nil),    // 11: com.yq.msg.CityMsg.PlayerCharacterImageMsg
	(*PupilDataMsg)(nil),               // 12: com.yq.msg.CityMsg.PupilDataMsg
	(*AttributeDataMsg)(nil),           // 13: com.yq.msg.CityMsg.AttributeDataMsg
}
var file_PupilRankActivity_proto_depIdxs = []int32{
	6,  // 0: com.yq.msg.CityMsg.EnterPupilRankActivityResp.rankList:type_name -> com.yq.msg.CityMsg.PupilRankRankData
	7,  // 1: com.yq.msg.CityMsg.GetIncreaseRecordResp.recordList:type_name -> com.yq.msg.CityMsg.PupilIncreaseRecordData
	6,  // 2: com.yq.msg.CityMsg.PupilRankRankListMsg.rankList:type_name -> com.yq.msg.CityMsg.PupilRankRankData
	11, // 3: com.yq.msg.CityMsg.PupilRankRankData.playerImageData:type_name -> com.yq.msg.CityMsg.PlayerCharacterImageMsg
	12, // 4: com.yq.msg.CityMsg.PupilRankRankData.pupilDataList:type_name -> com.yq.msg.CityMsg.PupilDataMsg
	13, // 5: com.yq.msg.CityMsg.PupilIncreaseRecordData.attData:type_name -> com.yq.msg.CityMsg.AttributeDataMsg
	10, // 6: com.yq.msg.CityMsg.PupilRankDetailResp.totalMsg:type_name -> com.yq.msg.CityMsg.PupilUpdateTotalMsg
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_PupilRankActivity_proto_init() }
func file_PupilRankActivity_proto_init() {
	if File_PupilRankActivity_proto != nil {
		return
	}
	file_Common_proto_init()
	file_Pupil_proto_init()
	file_WatchPlayer_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_PupilRankActivity_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EnterPupilRankActivityReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PupilRankActivity_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*EnterPupilRankActivityResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PupilRankActivity_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetIncreaseRecordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PupilRankActivity_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetIncreaseRecordResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PupilRankActivity_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*PupilRankRankListMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PupilRankActivity_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*PupilRankRankData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PupilRankActivity_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*PupilIncreaseRecordData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PupilRankActivity_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*PupilRankDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PupilRankActivity_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*PupilRankDetailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PupilRankActivity_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*PupilUpdateTotalMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PupilRankActivity_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PupilRankActivity_proto_goTypes,
		DependencyIndexes: file_PupilRankActivity_proto_depIdxs,
		EnumInfos:         file_PupilRankActivity_proto_enumTypes,
		MessageInfos:      file_PupilRankActivity_proto_msgTypes,
	}.Build()
	File_PupilRankActivity_proto = out.File
	file_PupilRankActivity_proto_rawDesc = nil
	file_PupilRankActivity_proto_goTypes = nil
	file_PupilRankActivity_proto_depIdxs = nil
}
