// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: Recharge.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreChargeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PreChargeType   *int32     `protobuf:"varint,1,opt,name=preChargeType" json:"preChargeType,omitempty"`
	MallId          *int32     `protobuf:"varint,2,opt,name=mallId" json:"mallId,omitempty"`
	ActivityId      *int32     `protobuf:"varint,3,opt,name=activityId" json:"activityId,omitempty"`
	SignParam       *SignParam `protobuf:"bytes,4,opt,name=signParam" json:"signParam,omitempty"`
	ExtraParam      []byte     `protobuf:"bytes,5,opt,name=extraParam" json:"extraParam,omitempty"`
	ClientPackageId *string    `protobuf:"bytes,6,opt,name=clientPackageId" json:"clientPackageId,omitempty"`
}

func (x *PreChargeReq) Reset() {
	*x = PreChargeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Recharge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreChargeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreChargeReq) ProtoMessage() {}

func (x *PreChargeReq) ProtoReflect() protoreflect.Message {
	mi := &file_Recharge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreChargeReq.ProtoReflect.Descriptor instead.
func (*PreChargeReq) Descriptor() ([]byte, []int) {
	return file_Recharge_proto_rawDescGZIP(), []int{0}
}

func (x *PreChargeReq) GetPreChargeType() int32 {
	if x != nil && x.PreChargeType != nil {
		return *x.PreChargeType
	}
	return 0
}

func (x *PreChargeReq) GetMallId() int32 {
	if x != nil && x.MallId != nil {
		return *x.MallId
	}
	return 0
}

func (x *PreChargeReq) GetActivityId() int32 {
	if x != nil && x.ActivityId != nil {
		return *x.ActivityId
	}
	return 0
}

func (x *PreChargeReq) GetSignParam() *SignParam {
	if x != nil {
		return x.SignParam
	}
	return nil
}

func (x *PreChargeReq) GetExtraParam() []byte {
	if x != nil {
		return x.ExtraParam
	}
	return nil
}

func (x *PreChargeReq) GetClientPackageId() string {
	if x != nil && x.ClientPackageId != nil {
		return *x.ClientPackageId
	}
	return ""
}

type ExtraParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SelectItem  []*HolidayCellSelectItemMsg `protobuf:"bytes,1,rep,name=selectItem" json:"selectItem,omitempty"`
	SendPresent *DoubleDemonsSendPresentMsg `protobuf:"bytes,2,opt,name=sendPresent" json:"sendPresent,omitempty"`
}

func (x *ExtraParam) Reset() {
	*x = ExtraParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Recharge_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtraParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtraParam) ProtoMessage() {}

func (x *ExtraParam) ProtoReflect() protoreflect.Message {
	mi := &file_Recharge_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtraParam.ProtoReflect.Descriptor instead.
func (*ExtraParam) Descriptor() ([]byte, []int) {
	return file_Recharge_proto_rawDescGZIP(), []int{1}
}

func (x *ExtraParam) GetSelectItem() []*HolidayCellSelectItemMsg {
	if x != nil {
		return x.SelectItem
	}
	return nil
}

func (x *ExtraParam) GetSendPresent() *DoubleDemonsSendPresentMsg {
	if x != nil {
		return x.SendPresent
	}
	return nil
}

type DoubleDemonsSendPresentMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId *int32  `protobuf:"varint,1,req,name=activityId" json:"activityId,omitempty"`
	PlayerId   *int64  `protobuf:"varint,2,req,name=playerId" json:"playerId,omitempty"`
	Words      *string `protobuf:"bytes,3,req,name=words" json:"words,omitempty"`
}

func (x *DoubleDemonsSendPresentMsg) Reset() {
	*x = DoubleDemonsSendPresentMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Recharge_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoubleDemonsSendPresentMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleDemonsSendPresentMsg) ProtoMessage() {}

func (x *DoubleDemonsSendPresentMsg) ProtoReflect() protoreflect.Message {
	mi := &file_Recharge_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleDemonsSendPresentMsg.ProtoReflect.Descriptor instead.
func (*DoubleDemonsSendPresentMsg) Descriptor() ([]byte, []int) {
	return file_Recharge_proto_rawDescGZIP(), []int{2}
}

func (x *DoubleDemonsSendPresentMsg) GetActivityId() int32 {
	if x != nil && x.ActivityId != nil {
		return *x.ActivityId
	}
	return 0
}

func (x *DoubleDemonsSendPresentMsg) GetPlayerId() int64 {
	if x != nil && x.PlayerId != nil {
		return *x.PlayerId
	}
	return 0
}

func (x *DoubleDemonsSendPresentMsg) GetWords() string {
	if x != nil && x.Words != nil {
		return *x.Words
	}
	return ""
}

type HolidayCellSelectItemMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index       *int32 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	SelectIndex *int32 `protobuf:"varint,2,opt,name=selectIndex" json:"selectIndex,omitempty"`
	ItemId      *int32 `protobuf:"varint,3,opt,name=ItemId" json:"ItemId,omitempty"`
	ItemNum     *int32 `protobuf:"varint,4,opt,name=ItemNum" json:"ItemNum,omitempty"`
}

func (x *HolidayCellSelectItemMsg) Reset() {
	*x = HolidayCellSelectItemMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Recharge_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HolidayCellSelectItemMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolidayCellSelectItemMsg) ProtoMessage() {}

func (x *HolidayCellSelectItemMsg) ProtoReflect() protoreflect.Message {
	mi := &file_Recharge_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolidayCellSelectItemMsg.ProtoReflect.Descriptor instead.
func (*HolidayCellSelectItemMsg) Descriptor() ([]byte, []int) {
	return file_Recharge_proto_rawDescGZIP(), []int{3}
}

func (x *HolidayCellSelectItemMsg) GetIndex() int32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *HolidayCellSelectItemMsg) GetSelectIndex() int32 {
	if x != nil && x.SelectIndex != nil {
		return *x.SelectIndex
	}
	return 0
}

func (x *HolidayCellSelectItemMsg) GetItemId() int32 {
	if x != nil && x.ItemId != nil {
		return *x.ItemId
	}
	return 0
}

func (x *HolidayCellSelectItemMsg) GetItemNum() int32 {
	if x != nil && x.ItemNum != nil {
		return *x.ItemNum
	}
	return 0
}

type PreChargeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret     *int32  `protobuf:"varint,1,req,name=ret" json:"ret,omitempty"`
	OrderNo *string `protobuf:"bytes,2,opt,name=orderNo" json:"orderNo,omitempty"`
	Sign    *string `protobuf:"bytes,3,opt,name=sign" json:"sign,omitempty"`
	Time    *int32  `protobuf:"varint,4,opt,name=time" json:"time,omitempty"`
}

func (x *PreChargeResp) Reset() {
	*x = PreChargeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Recharge_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreChargeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreChargeResp) ProtoMessage() {}

func (x *PreChargeResp) ProtoReflect() protoreflect.Message {
	mi := &file_Recharge_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreChargeResp.ProtoReflect.Descriptor instead.
func (*PreChargeResp) Descriptor() ([]byte, []int) {
	return file_Recharge_proto_rawDescGZIP(), []int{4}
}

func (x *PreChargeResp) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

func (x *PreChargeResp) GetOrderNo() string {
	if x != nil && x.OrderNo != nil {
		return *x.OrderNo
	}
	return ""
}

func (x *PreChargeResp) GetSign() string {
	if x != nil && x.Sign != nil {
		return *x.Sign
	}
	return ""
}

func (x *PreChargeResp) GetTime() int32 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

type NotifyRechargeSuccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reward *string `protobuf:"bytes,1,opt,name=reward" json:"reward,omitempty"`
	MallId *int32  `protobuf:"varint,2,opt,name=mallId" json:"mallId,omitempty"`
}

func (x *NotifyRechargeSuccess) Reset() {
	*x = NotifyRechargeSuccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Recharge_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyRechargeSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRechargeSuccess) ProtoMessage() {}

func (x *NotifyRechargeSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_Recharge_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRechargeSuccess.ProtoReflect.Descriptor instead.
func (*NotifyRechargeSuccess) Descriptor() ([]byte, []int) {
	return file_Recharge_proto_rawDescGZIP(), []int{5}
}

func (x *NotifyRechargeSuccess) GetReward() string {
	if x != nil && x.Reward != nil {
		return *x.Reward
	}
	return ""
}

func (x *NotifyRechargeSuccess) GetMallId() int32 {
	if x != nil && x.MallId != nil {
		return *x.MallId
	}
	return 0
}

type RechargeMallTimesSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RechargeMallTimesMsg []*RechargeMallTimesMsg `protobuf:"bytes,1,rep,name=rechargeMallTimesMsg" json:"rechargeMallTimesMsg,omitempty"`
}

func (x *RechargeMallTimesSync) Reset() {
	*x = RechargeMallTimesSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Recharge_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RechargeMallTimesSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeMallTimesSync) ProtoMessage() {}

func (x *RechargeMallTimesSync) ProtoReflect() protoreflect.Message {
	mi := &file_Recharge_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeMallTimesSync.ProtoReflect.Descriptor instead.
func (*RechargeMallTimesSync) Descriptor() ([]byte, []int) {
	return file_Recharge_proto_rawDescGZIP(), []int{6}
}

func (x *RechargeMallTimesSync) GetRechargeMallTimesMsg() []*RechargeMallTimesMsg {
	if x != nil {
		return x.RechargeMallTimesMsg
	}
	return nil
}

type RechargeMallTimesMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MallId *int32 `protobuf:"varint,1,opt,name=mallId" json:"mallId,omitempty"`
	Src    *int32 `protobuf:"varint,2,opt,name=src" json:"src,omitempty"`
	Times  *int32 `protobuf:"varint,3,opt,name=times" json:"times,omitempty"`
}

func (x *RechargeMallTimesMsg) Reset() {
	*x = RechargeMallTimesMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Recharge_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RechargeMallTimesMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeMallTimesMsg) ProtoMessage() {}

func (x *RechargeMallTimesMsg) ProtoReflect() protoreflect.Message {
	mi := &file_Recharge_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeMallTimesMsg.ProtoReflect.Descriptor instead.
func (*RechargeMallTimesMsg) Descriptor() ([]byte, []int) {
	return file_Recharge_proto_rawDescGZIP(), []int{7}
}

func (x *RechargeMallTimesMsg) GetMallId() int32 {
	if x != nil && x.MallId != nil {
		return *x.MallId
	}
	return 0
}

func (x *RechargeMallTimesMsg) GetSrc() int32 {
	if x != nil && x.Src != nil {
		return *x.Src
	}
	return 0
}

func (x *RechargeMallTimesMsg) GetTimes() int32 {
	if x != nil && x.Times != nil {
		return *x.Times
	}
	return 0
}

type SignParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Appid     *string `protobuf:"bytes,1,opt,name=appid" json:"appid,omitempty"`
	GameId    *string `protobuf:"bytes,2,opt,name=gameId" json:"gameId,omitempty"`
	Uid       *string `protobuf:"bytes,3,opt,name=uid" json:"uid,omitempty"`
	Sid       *string `protobuf:"bytes,4,opt,name=sid" json:"sid,omitempty"`
	ActorId   *string `protobuf:"bytes,5,opt,name=actorId" json:"actorId,omitempty"`
	Money     *string `protobuf:"bytes,6,opt,name=money" json:"money,omitempty"`
	ProductId *string `protobuf:"bytes,7,opt,name=productId" json:"productId,omitempty"`
	Subject   *string `protobuf:"bytes,8,opt,name=subject" json:"subject,omitempty"`
	GameCoin  *string `protobuf:"bytes,9,opt,name=gameCoin" json:"gameCoin,omitempty"`
	Ext       *string `protobuf:"bytes,10,opt,name=ext" json:"ext,omitempty"`
}

func (x *SignParam) Reset() {
	*x = SignParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Recharge_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignParam) ProtoMessage() {}

func (x *SignParam) ProtoReflect() protoreflect.Message {
	mi := &file_Recharge_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignParam.ProtoReflect.Descriptor instead.
func (*SignParam) Descriptor() ([]byte, []int) {
	return file_Recharge_proto_rawDescGZIP(), []int{8}
}

func (x *SignParam) GetAppid() string {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return ""
}

func (x *SignParam) GetGameId() string {
	if x != nil && x.GameId != nil {
		return *x.GameId
	}
	return ""
}

func (x *SignParam) GetUid() string {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return ""
}

func (x *SignParam) GetSid() string {
	if x != nil && x.Sid != nil {
		return *x.Sid
	}
	return ""
}

func (x *SignParam) GetActorId() string {
	if x != nil && x.ActorId != nil {
		return *x.ActorId
	}
	return ""
}

func (x *SignParam) GetMoney() string {
	if x != nil && x.Money != nil {
		return *x.Money
	}
	return ""
}

func (x *SignParam) GetProductId() string {
	if x != nil && x.ProductId != nil {
		return *x.ProductId
	}
	return ""
}

func (x *SignParam) GetSubject() string {
	if x != nil && x.Subject != nil {
		return *x.Subject
	}
	return ""
}

func (x *SignParam) GetGameCoin() string {
	if x != nil && x.GameCoin != nil {
		return *x.GameCoin
	}
	return ""
}

func (x *SignParam) GetExt() string {
	if x != nil && x.Ext != nil {
		return *x.Ext
	}
	return ""
}

type MallChanceUseReqMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopType   *int32 `protobuf:"varint,1,req,name=shopType" json:"shopType,omitempty"`
	MallId     *int32 `protobuf:"varint,2,req,name=mallId" json:"mallId,omitempty"`
	Count      *int32 `protobuf:"varint,3,req,name=count" json:"count,omitempty"`
	ActivityId *int32 `protobuf:"varint,4,opt,name=activityId" json:"activityId,omitempty"`
	ExtraParam []byte `protobuf:"bytes,5,opt,name=extraParam" json:"extraParam,omitempty"`
}

func (x *MallChanceUseReqMsg) Reset() {
	*x = MallChanceUseReqMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Recharge_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MallChanceUseReqMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MallChanceUseReqMsg) ProtoMessage() {}

func (x *MallChanceUseReqMsg) ProtoReflect() protoreflect.Message {
	mi := &file_Recharge_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MallChanceUseReqMsg.ProtoReflect.Descriptor instead.
func (*MallChanceUseReqMsg) Descriptor() ([]byte, []int) {
	return file_Recharge_proto_rawDescGZIP(), []int{9}
}

func (x *MallChanceUseReqMsg) GetShopType() int32 {
	if x != nil && x.ShopType != nil {
		return *x.ShopType
	}
	return 0
}

func (x *MallChanceUseReqMsg) GetMallId() int32 {
	if x != nil && x.MallId != nil {
		return *x.MallId
	}
	return 0
}

func (x *MallChanceUseReqMsg) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *MallChanceUseReqMsg) GetActivityId() int32 {
	if x != nil && x.ActivityId != nil {
		return *x.ActivityId
	}
	return 0
}

func (x *MallChanceUseReqMsg) GetExtraParam() []byte {
	if x != nil {
		return x.ExtraParam
	}
	return nil
}

type MallChanceUseRespMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    *int32  `protobuf:"varint,1,req,name=ret" json:"ret,omitempty"`
	Reward *string `protobuf:"bytes,2,opt,name=reward" json:"reward,omitempty"`
}

func (x *MallChanceUseRespMsg) Reset() {
	*x = MallChanceUseRespMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Recharge_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MallChanceUseRespMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MallChanceUseRespMsg) ProtoMessage() {}

func (x *MallChanceUseRespMsg) ProtoReflect() protoreflect.Message {
	mi := &file_Recharge_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MallChanceUseRespMsg.ProtoReflect.Descriptor instead.
func (*MallChanceUseRespMsg) Descriptor() ([]byte, []int) {
	return file_Recharge_proto_rawDescGZIP(), []int{10}
}

func (x *MallChanceUseRespMsg) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

func (x *MallChanceUseRespMsg) GetReward() string {
	if x != nil && x.Reward != nil {
		return *x.Reward
	}
	return ""
}

var File_Recharge_proto protoreflect.FileDescriptor

var file_Recharge_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x69, 0x74,
	0x79, 0x4d, 0x73, 0x67, 0x22, 0xf3, 0x01, 0x0a, 0x0c, 0x50, 0x72, 0x65, 0x43, 0x68, 0x61, 0x72,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x72, 0x65, 0x43, 0x68, 0x61, 0x72,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x70, 0x72,
	0x65, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x61, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x61, 0x6c,
	0x6c, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x49, 0x64, 0x12, 0x3b, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x79, 0x71, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x2e, 0x53, 0x69, 0x67, 0x6e,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x74, 0x72, 0x61, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x65, 0x78, 0x74, 0x72, 0x61, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x12, 0x28, 0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0xac, 0x01, 0x0a, 0x0a, 0x45,
	0x78, 0x74, 0x72, 0x61, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x4c, 0x0a, 0x0a, 0x73, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e,
	0x63, 0x6f, 0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d,
	0x73, 0x67, 0x2e, 0x48, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x43, 0x65, 0x6c, 0x6c, 0x53, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x4d, 0x73, 0x67, 0x52, 0x0a, 0x73, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x50, 0x0a, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x50,
	0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d, 0x73,
	0x67, 0x2e, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x6d, 0x6f, 0x6e, 0x73, 0x53, 0x65,
	0x6e, 0x64, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x52, 0x0b, 0x73, 0x65,
	0x6e, 0x64, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x22, 0x6e, 0x0a, 0x1a, 0x44, 0x6f, 0x75,
	0x62, 0x6c, 0x65, 0x44, 0x65, 0x6d, 0x6f, 0x6e, 0x73, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x72, 0x65,
	0x73, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x03, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x05, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x84, 0x01, 0x0a, 0x18, 0x48, 0x6f,
	0x6c, 0x69, 0x64, 0x61, 0x79, 0x43, 0x65, 0x6c, 0x6c, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x20, 0x0a, 0x0b,
	0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x16,
	0x0a, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x75,
	0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x75, 0x6d,
	0x22, 0x63, 0x0a, 0x0d, 0x50, 0x72, 0x65, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x03,
	0x72, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x67,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x47, 0x0a, 0x15, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52,
	0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x6c, 0x6c, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x22, 0x75,
	0x0a, 0x15, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x4d, 0x61, 0x6c, 0x6c, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x5c, 0x0a, 0x14, 0x72, 0x65, 0x63, 0x68, 0x61,
	0x72, 0x67, 0x65, 0x4d, 0x61, 0x6c, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x4d, 0x73, 0x67, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x2e, 0x52, 0x65, 0x63, 0x68, 0x61,
	0x72, 0x67, 0x65, 0x4d, 0x61, 0x6c, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x4d, 0x73, 0x67, 0x52,
	0x14, 0x72, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x4d, 0x61, 0x6c, 0x6c, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x4d, 0x73, 0x67, 0x22, 0x56, 0x0a, 0x14, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67,
	0x65, 0x4d, 0x61, 0x6c, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x4d, 0x73, 0x67, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d,
	0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x22, 0xf3, 0x01,
	0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x70, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x1c, 0x0a,
	0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x69,
	0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x69,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x65, 0x78, 0x74, 0x22, 0x9f, 0x01, 0x0a, 0x13, 0x4d, 0x61, 0x6c, 0x6c, 0x43, 0x68, 0x61, 0x6e,
	0x63, 0x65, 0x55, 0x73, 0x65, 0x52, 0x65, 0x71, 0x4d, 0x73, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x68, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x08, 0x73,
	0x68, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x6c, 0x6c, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x02, 0x28, 0x05, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x74, 0x72, 0x61, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x65, 0x78, 0x74, 0x72, 0x61,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x22, 0x40, 0x0a, 0x14, 0x4d, 0x61, 0x6c, 0x6c, 0x43, 0x68, 0x61,
	0x6e, 0x63, 0x65, 0x55, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6d, 0x7a, 0x68, 0x6f, 0x6e, 0x67, 0x71, 0x69, 0x2f,
	0x78, 0x64, 0x64, 0x71, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x61, 0x6d, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62,
}

var (
	file_Recharge_proto_rawDescOnce sync.Once
	file_Recharge_proto_rawDescData = file_Recharge_proto_rawDesc
)

func file_Recharge_proto_rawDescGZIP() []byte {
	file_Recharge_proto_rawDescOnce.Do(func() {
		file_Recharge_proto_rawDescData = protoimpl.X.CompressGZIP(file_Recharge_proto_rawDescData)
	})
	return file_Recharge_proto_rawDescData
}

var file_Recharge_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_Recharge_proto_goTypes = []any{
	(*PreChargeReq)(nil),               // 0: com.yq.msg.CityMsg.PreChargeReq
	(*ExtraParam)(nil),                 // 1: com.yq.msg.CityMsg.ExtraParam
	(*DoubleDemonsSendPresentMsg)(nil), // 2: com.yq.msg.CityMsg.DoubleDemonsSendPresentMsg
	(*HolidayCellSelectItemMsg)(nil),   // 3: com.yq.msg.CityMsg.HolidayCellSelectItemMsg
	(*PreChargeResp)(nil),              // 4: com.yq.msg.CityMsg.PreChargeResp
	(*NotifyRechargeSuccess)(nil),      // 5: com.yq.msg.CityMsg.NotifyRechargeSuccess
	(*RechargeMallTimesSync)(nil),      // 6: com.yq.msg.CityMsg.RechargeMallTimesSync
	(*RechargeMallTimesMsg)(nil),       // 7: com.yq.msg.CityMsg.RechargeMallTimesMsg
	(*SignParam)(nil),                  // 8: com.yq.msg.CityMsg.SignParam
	(*MallChanceUseReqMsg)(nil),        // 9: com.yq.msg.CityMsg.MallChanceUseReqMsg
	(*MallChanceUseRespMsg)(nil),       // 10: com.yq.msg.CityMsg.MallChanceUseRespMsg
}
var file_Recharge_proto_depIdxs = []int32{
	8, // 0: com.yq.msg.CityMsg.PreChargeReq.signParam:type_name -> com.yq.msg.CityMsg.SignParam
	3, // 1: com.yq.msg.CityMsg.ExtraParam.selectItem:type_name -> com.yq.msg.CityMsg.HolidayCellSelectItemMsg
	2, // 2: com.yq.msg.CityMsg.ExtraParam.sendPresent:type_name -> com.yq.msg.CityMsg.DoubleDemonsSendPresentMsg
	7, // 3: com.yq.msg.CityMsg.RechargeMallTimesSync.rechargeMallTimesMsg:type_name -> com.yq.msg.CityMsg.RechargeMallTimesMsg
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_Recharge_proto_init() }
func file_Recharge_proto_init() {
	if File_Recharge_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Recharge_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PreChargeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Recharge_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ExtraParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Recharge_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*DoubleDemonsSendPresentMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Recharge_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*HolidayCellSelectItemMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Recharge_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*PreChargeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Recharge_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*NotifyRechargeSuccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Recharge_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*RechargeMallTimesSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Recharge_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*RechargeMallTimesMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Recharge_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*SignParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Recharge_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*MallChanceUseReqMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Recharge_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*MallChanceUseRespMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Recharge_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Recharge_proto_goTypes,
		DependencyIndexes: file_Recharge_proto_depIdxs,
		MessageInfos:      file_Recharge_proto_msgTypes,
	}.Build()
	File_Recharge_proto = out.File
	file_Recharge_proto_rawDesc = nil
	file_Recharge_proto_goTypes = nil
	file_Recharge_proto_depIdxs = nil
}
