// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: RegressionActivity.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegressionActivityConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecallDrawConfig []*RecallDrawConfig `protobuf:"bytes,1,rep,name=recallDrawConfig" json:"recallDrawConfig,omitempty"`
}

func (x *RegressionActivityConfig) Reset() {
	*x = RegressionActivityConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegressionActivity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegressionActivityConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegressionActivityConfig) ProtoMessage() {}

func (x *RegressionActivityConfig) ProtoReflect() protoreflect.Message {
	mi := &file_RegressionActivity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegressionActivityConfig.ProtoReflect.Descriptor instead.
func (*RegressionActivityConfig) Descriptor() ([]byte, []int) {
	return file_RegressionActivity_proto_rawDescGZIP(), []int{0}
}

func (x *RegressionActivityConfig) GetRecallDrawConfig() []*RecallDrawConfig {
	if x != nil {
		return x.RecallDrawConfig
	}
	return nil
}

type RecallDrawConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          *int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	IsBigReward *int32  `protobuf:"varint,2,opt,name=isBigReward" json:"isBigReward,omitempty"`
	Reward      *string `protobuf:"bytes,3,opt,name=reward" json:"reward,omitempty"`
}

func (x *RecallDrawConfig) Reset() {
	*x = RecallDrawConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegressionActivity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecallDrawConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallDrawConfig) ProtoMessage() {}

func (x *RecallDrawConfig) ProtoReflect() protoreflect.Message {
	mi := &file_RegressionActivity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallDrawConfig.ProtoReflect.Descriptor instead.
func (*RecallDrawConfig) Descriptor() ([]byte, []int) {
	return file_RegressionActivity_proto_rawDescGZIP(), []int{1}
}

func (x *RecallDrawConfig) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *RecallDrawConfig) GetIsBigReward() int32 {
	if x != nil && x.IsBigReward != nil {
		return *x.IsBigReward
	}
	return 0
}

func (x *RecallDrawConfig) GetReward() string {
	if x != nil && x.Reward != nil {
		return *x.Reward
	}
	return ""
}

type RegressionShareReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegressionShareReq) Reset() {
	*x = RegressionShareReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegressionActivity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegressionShareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegressionShareReq) ProtoMessage() {}

func (x *RegressionShareReq) ProtoReflect() protoreflect.Message {
	mi := &file_RegressionActivity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegressionShareReq.ProtoReflect.Descriptor instead.
func (*RegressionShareReq) Descriptor() ([]byte, []int) {
	return file_RegressionActivity_proto_rawDescGZIP(), []int{2}
}

type RegressionShareResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret *int32 `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
}

func (x *RegressionShareResp) Reset() {
	*x = RegressionShareResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegressionActivity_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegressionShareResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegressionShareResp) ProtoMessage() {}

func (x *RegressionShareResp) ProtoReflect() protoreflect.Message {
	mi := &file_RegressionActivity_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegressionShareResp.ProtoReflect.Descriptor instead.
func (*RegressionShareResp) Descriptor() ([]byte, []int) {
	return file_RegressionActivity_proto_rawDescGZIP(), []int{3}
}

func (x *RegressionShareResp) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

type RegressionLotteryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegressionLotteryReq) Reset() {
	*x = RegressionLotteryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegressionActivity_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegressionLotteryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegressionLotteryReq) ProtoMessage() {}

func (x *RegressionLotteryReq) ProtoReflect() protoreflect.Message {
	mi := &file_RegressionActivity_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegressionLotteryReq.ProtoReflect.Descriptor instead.
func (*RegressionLotteryReq) Descriptor() ([]byte, []int) {
	return file_RegressionActivity_proto_rawDescGZIP(), []int{4}
}

type RegressionLotteryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret                    *int32                  `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	RegressionSelectReward *RegressionSelectReward `protobuf:"bytes,2,opt,name=regressionSelectReward" json:"regressionSelectReward,omitempty"`
}

func (x *RegressionLotteryResp) Reset() {
	*x = RegressionLotteryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegressionActivity_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegressionLotteryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegressionLotteryResp) ProtoMessage() {}

func (x *RegressionLotteryResp) ProtoReflect() protoreflect.Message {
	mi := &file_RegressionActivity_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegressionLotteryResp.ProtoReflect.Descriptor instead.
func (*RegressionLotteryResp) Descriptor() ([]byte, []int) {
	return file_RegressionActivity_proto_rawDescGZIP(), []int{5}
}

func (x *RegressionLotteryResp) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

func (x *RegressionLotteryResp) GetRegressionSelectReward() *RegressionSelectReward {
	if x != nil {
		return x.RegressionSelectReward
	}
	return nil
}

type GetRegressionPlayerDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRegressionPlayerDataReq) Reset() {
	*x = GetRegressionPlayerDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegressionActivity_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRegressionPlayerDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegressionPlayerDataReq) ProtoMessage() {}

func (x *GetRegressionPlayerDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_RegressionActivity_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegressionPlayerDataReq.ProtoReflect.Descriptor instead.
func (*GetRegressionPlayerDataReq) Descriptor() ([]byte, []int) {
	return file_RegressionActivity_proto_rawDescGZIP(), []int{6}
}

type GetRegressionPlayerDataResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret                  *int32                  `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	RegressionPlayerData []*RegressionPlayerData `protobuf:"bytes,2,rep,name=regressionPlayerData" json:"regressionPlayerData,omitempty"`
}

func (x *GetRegressionPlayerDataResp) Reset() {
	*x = GetRegressionPlayerDataResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegressionActivity_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRegressionPlayerDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegressionPlayerDataResp) ProtoMessage() {}

func (x *GetRegressionPlayerDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_RegressionActivity_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegressionPlayerDataResp.ProtoReflect.Descriptor instead.
func (*GetRegressionPlayerDataResp) Descriptor() ([]byte, []int) {
	return file_RegressionActivity_proto_rawDescGZIP(), []int{7}
}

func (x *GetRegressionPlayerDataResp) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

func (x *GetRegressionPlayerDataResp) GetRegressionPlayerData() []*RegressionPlayerData {
	if x != nil {
		return x.RegressionPlayerData
	}
	return nil
}

type RegressionPlayerData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerBaseDataMsg  *PlayerBaseDataMsg    `protobuf:"bytes,1,opt,name=playerBaseDataMsg" json:"playerBaseDataMsg,omitempty"`
	LastLoginTime      *int64                `protobuf:"varint,2,opt,name=lastLoginTime" json:"lastLoginTime,omitempty"`
	RegressionTaskData []*RegressionTaskData `protobuf:"bytes,3,rep,name=regressionTaskData" json:"regressionTaskData,omitempty"`
	OpenId             *string               `protobuf:"bytes,4,opt,name=openId" json:"openId,omitempty"`
}

func (x *RegressionPlayerData) Reset() {
	*x = RegressionPlayerData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegressionActivity_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegressionPlayerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegressionPlayerData) ProtoMessage() {}

func (x *RegressionPlayerData) ProtoReflect() protoreflect.Message {
	mi := &file_RegressionActivity_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegressionPlayerData.ProtoReflect.Descriptor instead.
func (*RegressionPlayerData) Descriptor() ([]byte, []int) {
	return file_RegressionActivity_proto_rawDescGZIP(), []int{8}
}

func (x *RegressionPlayerData) GetPlayerBaseDataMsg() *PlayerBaseDataMsg {
	if x != nil {
		return x.PlayerBaseDataMsg
	}
	return nil
}

func (x *RegressionPlayerData) GetLastLoginTime() int64 {
	if x != nil && x.LastLoginTime != nil {
		return *x.LastLoginTime
	}
	return 0
}

func (x *RegressionPlayerData) GetRegressionTaskData() []*RegressionTaskData {
	if x != nil {
		return x.RegressionTaskData
	}
	return nil
}

func (x *RegressionPlayerData) GetOpenId() string {
	if x != nil && x.OpenId != nil {
		return *x.OpenId
	}
	return ""
}

type RegressionTaskData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId *int32 `protobuf:"varint,1,opt,name=taskId" json:"taskId,omitempty"`
	Value  *int32 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	Status *int32 `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
}

func (x *RegressionTaskData) Reset() {
	*x = RegressionTaskData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegressionActivity_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegressionTaskData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegressionTaskData) ProtoMessage() {}

func (x *RegressionTaskData) ProtoReflect() protoreflect.Message {
	mi := &file_RegressionActivity_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegressionTaskData.ProtoReflect.Descriptor instead.
func (*RegressionTaskData) Descriptor() ([]byte, []int) {
	return file_RegressionActivity_proto_rawDescGZIP(), []int{9}
}

func (x *RegressionTaskData) GetTaskId() int32 {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return 0
}

func (x *RegressionTaskData) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *RegressionTaskData) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

type GetRegressionReceiveRewardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpenId *string `protobuf:"bytes,1,opt,name=openId" json:"openId,omitempty"`
	TaskId *int32  `protobuf:"varint,2,opt,name=taskId" json:"taskId,omitempty"`
}

func (x *GetRegressionReceiveRewardReq) Reset() {
	*x = GetRegressionReceiveRewardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegressionActivity_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRegressionReceiveRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegressionReceiveRewardReq) ProtoMessage() {}

func (x *GetRegressionReceiveRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_RegressionActivity_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegressionReceiveRewardReq.ProtoReflect.Descriptor instead.
func (*GetRegressionReceiveRewardReq) Descriptor() ([]byte, []int) {
	return file_RegressionActivity_proto_rawDescGZIP(), []int{10}
}

func (x *GetRegressionReceiveRewardReq) GetOpenId() string {
	if x != nil && x.OpenId != nil {
		return *x.OpenId
	}
	return ""
}

func (x *GetRegressionReceiveRewardReq) GetTaskId() int32 {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return 0
}

type GetRegressionReceiveRewardResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    *int32  `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	Reward *string `protobuf:"bytes,2,opt,name=reward" json:"reward,omitempty"`
}

func (x *GetRegressionReceiveRewardResp) Reset() {
	*x = GetRegressionReceiveRewardResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegressionActivity_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRegressionReceiveRewardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegressionReceiveRewardResp) ProtoMessage() {}

func (x *GetRegressionReceiveRewardResp) ProtoReflect() protoreflect.Message {
	mi := &file_RegressionActivity_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegressionReceiveRewardResp.ProtoReflect.Descriptor instead.
func (*GetRegressionReceiveRewardResp) Descriptor() ([]byte, []int) {
	return file_RegressionActivity_proto_rawDescGZIP(), []int{11}
}

func (x *GetRegressionReceiveRewardResp) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

func (x *GetRegressionReceiveRewardResp) GetReward() string {
	if x != nil && x.Reward != nil {
		return *x.Reward
	}
	return ""
}

type RegressionSaveSelectItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegressionSelectReward *RegressionSelectReward `protobuf:"bytes,1,opt,name=regressionSelectReward" json:"regressionSelectReward,omitempty"`
}

func (x *RegressionSaveSelectItemReq) Reset() {
	*x = RegressionSaveSelectItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegressionActivity_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegressionSaveSelectItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegressionSaveSelectItemReq) ProtoMessage() {}

func (x *RegressionSaveSelectItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_RegressionActivity_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegressionSaveSelectItemReq.ProtoReflect.Descriptor instead.
func (*RegressionSaveSelectItemReq) Descriptor() ([]byte, []int) {
	return file_RegressionActivity_proto_rawDescGZIP(), []int{12}
}

func (x *RegressionSaveSelectItemReq) GetRegressionSelectReward() *RegressionSelectReward {
	if x != nil {
		return x.RegressionSelectReward
	}
	return nil
}

type RegressionSaveSelectItemResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret *int32 `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
}

func (x *RegressionSaveSelectItemResp) Reset() {
	*x = RegressionSaveSelectItemResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegressionActivity_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegressionSaveSelectItemResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegressionSaveSelectItemResp) ProtoMessage() {}

func (x *RegressionSaveSelectItemResp) ProtoReflect() protoreflect.Message {
	mi := &file_RegressionActivity_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegressionSaveSelectItemResp.ProtoReflect.Descriptor instead.
func (*RegressionSaveSelectItemResp) Descriptor() ([]byte, []int) {
	return file_RegressionActivity_proto_rawDescGZIP(), []int{13}
}

func (x *RegressionSaveSelectItemResp) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

var File_RegressionActivity_proto protoreflect.FileDescriptor

var file_RegressionActivity_proto_rawDesc = []byte{
	0x0a, 0x18, 0x52, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x63, 0x6f, 0x6d, 0x2e,
	0x79, 0x71, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x1a, 0x0c,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x50, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x6c, 0x0a, 0x18, 0x52, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x50, 0x0a, 0x10,
	0x72, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x44, 0x72, 0x61, 0x77, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x79, 0x71, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x2e, 0x52, 0x65, 0x63, 0x61,
	0x6c, 0x6c, 0x44, 0x72, 0x61, 0x77, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x10, 0x72, 0x65,
	0x63, 0x61, 0x6c, 0x6c, 0x44, 0x72, 0x61, 0x77, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x5c,
	0x0a, 0x10, 0x52, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x44, 0x72, 0x61, 0x77, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x73, 0x42, 0x69, 0x67, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x69, 0x73, 0x42, 0x69, 0x67, 0x52, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x22, 0x14, 0x0a, 0x12,
	0x52, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x22, 0x27, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x52,
	0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x22, 0x8d, 0x01, 0x0a, 0x15, 0x52, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x4c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12,
	0x62, 0x0a, 0x16, 0x72, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x69, 0x74,
	0x79, 0x4d, 0x73, 0x67, 0x2e, 0x52, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x16, 0x72, 0x65, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x22, 0x1c, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x22, 0x8d, 0x01, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x72, 0x65, 0x74, 0x12, 0x5c, 0x0a, 0x14, 0x72, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x28, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43,
	0x69, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x2e, 0x52, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x14, 0x72, 0x65, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x81, 0x02, 0x0a, 0x14, 0x52, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x53, 0x0a, 0x11, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x73, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x42, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x73, 0x67, 0x52, 0x11, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x73, 0x67, 0x12,
	0x24, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x56, 0x0a, 0x12, 0x72, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43,
	0x69, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x2e, 0x52, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x52, 0x12, 0x72, 0x65, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f,
	0x70, 0x65, 0x6e, 0x49, 0x64, 0x22, 0x5a, 0x0a, 0x12, 0x52, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x73,
	0x6b, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x4f, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61,
	0x73, 0x6b, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b,
	0x49, 0x64, 0x22, 0x4a, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x22, 0x81,
	0x01, 0x0a, 0x1b, 0x52, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x61, 0x76,
	0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x62,
	0x0a, 0x16, 0x72, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x69, 0x74, 0x79,
	0x4d, 0x73, 0x67, 0x2e, 0x52, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x16, 0x72, 0x65, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x22, 0x30, 0x0a, 0x1c, 0x52, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x53, 0x61, 0x76, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x72, 0x65, 0x74, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x69, 0x6d, 0x7a, 0x68, 0x6f, 0x6e, 0x67, 0x71, 0x69, 0x2f, 0x78, 0x64, 0x64,
	0x71, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62,
}

var (
	file_RegressionActivity_proto_rawDescOnce sync.Once
	file_RegressionActivity_proto_rawDescData = file_RegressionActivity_proto_rawDesc
)

func file_RegressionActivity_proto_rawDescGZIP() []byte {
	file_RegressionActivity_proto_rawDescOnce.Do(func() {
		file_RegressionActivity_proto_rawDescData = protoimpl.X.CompressGZIP(file_RegressionActivity_proto_rawDescData)
	})
	return file_RegressionActivity_proto_rawDescData
}

var file_RegressionActivity_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_RegressionActivity_proto_goTypes = []any{
	(*RegressionActivityConfig)(nil),       // 0: com.yq.msg.CityMsg.RegressionActivityConfig
	(*RecallDrawConfig)(nil),               // 1: com.yq.msg.CityMsg.RecallDrawConfig
	(*RegressionShareReq)(nil),             // 2: com.yq.msg.CityMsg.RegressionShareReq
	(*RegressionShareResp)(nil),            // 3: com.yq.msg.CityMsg.RegressionShareResp
	(*RegressionLotteryReq)(nil),           // 4: com.yq.msg.CityMsg.RegressionLotteryReq
	(*RegressionLotteryResp)(nil),          // 5: com.yq.msg.CityMsg.RegressionLotteryResp
	(*GetRegressionPlayerDataReq)(nil),     // 6: com.yq.msg.CityMsg.GetRegressionPlayerDataReq
	(*GetRegressionPlayerDataResp)(nil),    // 7: com.yq.msg.CityMsg.GetRegressionPlayerDataResp
	(*RegressionPlayerData)(nil),           // 8: com.yq.msg.CityMsg.RegressionPlayerData
	(*RegressionTaskData)(nil),             // 9: com.yq.msg.CityMsg.RegressionTaskData
	(*GetRegressionReceiveRewardReq)(nil),  // 10: com.yq.msg.CityMsg.GetRegressionReceiveRewardReq
	(*GetRegressionReceiveRewardResp)(nil), // 11: com.yq.msg.CityMsg.GetRegressionReceiveRewardResp
	(*RegressionSaveSelectItemReq)(nil),    // 12: com.yq.msg.CityMsg.RegressionSaveSelectItemReq
	(*RegressionSaveSelectItemResp)(nil),   // 13: com.yq.msg.CityMsg.RegressionSaveSelectItemResp
	(*RegressionSelectReward)(nil),         // 14: com.yq.msg.CityMsg.RegressionSelectReward
	(*PlayerBaseDataMsg)(nil),              // 15: com.yq.msg.CityMsg.PlayerBaseDataMsg
}
var file_RegressionActivity_proto_depIdxs = []int32{
	1,  // 0: com.yq.msg.CityMsg.RegressionActivityConfig.recallDrawConfig:type_name -> com.yq.msg.CityMsg.RecallDrawConfig
	14, // 1: com.yq.msg.CityMsg.RegressionLotteryResp.regressionSelectReward:type_name -> com.yq.msg.CityMsg.RegressionSelectReward
	8,  // 2: com.yq.msg.CityMsg.GetRegressionPlayerDataResp.regressionPlayerData:type_name -> com.yq.msg.CityMsg.RegressionPlayerData
	15, // 3: com.yq.msg.CityMsg.RegressionPlayerData.playerBaseDataMsg:type_name -> com.yq.msg.CityMsg.PlayerBaseDataMsg
	9,  // 4: com.yq.msg.CityMsg.RegressionPlayerData.regressionTaskData:type_name -> com.yq.msg.CityMsg.RegressionTaskData
	14, // 5: com.yq.msg.CityMsg.RegressionSaveSelectItemReq.regressionSelectReward:type_name -> com.yq.msg.CityMsg.RegressionSelectReward
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_RegressionActivity_proto_init() }
func file_RegressionActivity_proto_init() {
	if File_RegressionActivity_proto != nil {
		return
	}
	file_Common_proto_init()
	file_PackagesBase_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_RegressionActivity_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RegressionActivityConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegressionActivity_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RecallDrawConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegressionActivity_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*RegressionShareReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegressionActivity_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*RegressionShareResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegressionActivity_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*RegressionLotteryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegressionActivity_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*RegressionLotteryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegressionActivity_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetRegressionPlayerDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegressionActivity_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetRegressionPlayerDataResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegressionActivity_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*RegressionPlayerData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegressionActivity_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*RegressionTaskData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegressionActivity_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*GetRegressionReceiveRewardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegressionActivity_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*GetRegressionReceiveRewardResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegressionActivity_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*RegressionSaveSelectItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegressionActivity_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*RegressionSaveSelectItemResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_RegressionActivity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_RegressionActivity_proto_goTypes,
		DependencyIndexes: file_RegressionActivity_proto_depIdxs,
		MessageInfos:      file_RegressionActivity_proto_msgTypes,
	}.Build()
	File_RegressionActivity_proto = out.File
	file_RegressionActivity_proto_rawDesc = nil
	file_RegressionActivity_proto_goTypes = nil
	file_RegressionActivity_proto_depIdxs = nil
}
