// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: SystemShield.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemShieldSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShieldList []int32 `protobuf:"varint,1,rep,name=shieldList" json:"shieldList,omitempty"`
}

func (x *SystemShieldSync) Reset() {
	*x = SystemShieldSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SystemShield_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemShieldSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemShieldSync) ProtoMessage() {}

func (x *SystemShieldSync) ProtoReflect() protoreflect.Message {
	mi := &file_SystemShield_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemShieldSync.ProtoReflect.Descriptor instead.
func (*SystemShieldSync) Descriptor() ([]byte, []int) {
	return file_SystemShield_proto_rawDescGZIP(), []int{0}
}

func (x *SystemShieldSync) GetShieldList() []int32 {
	if x != nil {
		return x.ShieldList
	}
	return nil
}

var File_SystemShield_proto protoreflect.FileDescriptor

var file_SystemShield_proto_rawDesc = []byte{
	0x0a, 0x12, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x68, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x22, 0x32, 0x0a, 0x10, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x53, 0x68, 0x69, 0x65, 0x6c, 0x64, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x68, 0x69, 0x65, 0x6c, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x0a, 0x73, 0x68, 0x69, 0x65, 0x6c, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x36, 0x5a, 0x34,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6d, 0x7a, 0x68, 0x6f,
	0x6e, 0x67, 0x71, 0x69, 0x2f, 0x78, 0x64, 0x64, 0x71, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70,
	0x62, 0x3b, 0x70, 0x62,
}

var (
	file_SystemShield_proto_rawDescOnce sync.Once
	file_SystemShield_proto_rawDescData = file_SystemShield_proto_rawDesc
)

func file_SystemShield_proto_rawDescGZIP() []byte {
	file_SystemShield_proto_rawDescOnce.Do(func() {
		file_SystemShield_proto_rawDescData = protoimpl.X.CompressGZIP(file_SystemShield_proto_rawDescData)
	})
	return file_SystemShield_proto_rawDescData
}

var file_SystemShield_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SystemShield_proto_goTypes = []any{
	(*SystemShieldSync)(nil), // 0: com.yq.msg.CityMsg.SystemShieldSync
}
var file_SystemShield_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_SystemShield_proto_init() }
func file_SystemShield_proto_init() {
	if File_SystemShield_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_SystemShield_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SystemShieldSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SystemShield_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SystemShield_proto_goTypes,
		DependencyIndexes: file_SystemShield_proto_depIdxs,
		MessageInfos:      file_SystemShield_proto_msgTypes,
	}.Build()
	File_SystemShield_proto = out.File
	file_SystemShield_proto_rawDesc = nil
	file_SystemShield_proto_goTypes = nil
	file_SystemShield_proto_depIdxs = nil
}
