// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: WestTravel.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WestTravelActivityPlayerDataMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId *int32 `protobuf:"varint,1,req,name=activityId" json:"activityId,omitempty"`
	MaxLevel   *int32 `protobuf:"varint,2,req,name=maxLevel" json:"maxLevel,omitempty"`
}

func (x *WestTravelActivityPlayerDataMsg) Reset() {
	*x = WestTravelActivityPlayerDataMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WestTravel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WestTravelActivityPlayerDataMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WestTravelActivityPlayerDataMsg) ProtoMessage() {}

func (x *WestTravelActivityPlayerDataMsg) ProtoReflect() protoreflect.Message {
	mi := &file_WestTravel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WestTravelActivityPlayerDataMsg.ProtoReflect.Descriptor instead.
func (*WestTravelActivityPlayerDataMsg) Descriptor() ([]byte, []int) {
	return file_WestTravel_proto_rawDescGZIP(), []int{0}
}

func (x *WestTravelActivityPlayerDataMsg) GetActivityId() int32 {
	if x != nil && x.ActivityId != nil {
		return *x.ActivityId
	}
	return 0
}

func (x *WestTravelActivityPlayerDataMsg) GetMaxLevel() int32 {
	if x != nil && x.MaxLevel != nil {
		return *x.MaxLevel
	}
	return 0
}

type WestTravelData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           *int32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	BackgroundID *int32 `protobuf:"varint,2,req,name=backgroundID" json:"backgroundID,omitempty"`
	LevelType    *int32 `protobuf:"varint,3,req,name=levelType" json:"levelType,omitempty"`
	UnlockTime   *int64 `protobuf:"varint,4,req,name=unlockTime" json:"unlockTime,omitempty"`
}

func (x *WestTravelData) Reset() {
	*x = WestTravelData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WestTravel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WestTravelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WestTravelData) ProtoMessage() {}

func (x *WestTravelData) ProtoReflect() protoreflect.Message {
	mi := &file_WestTravel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WestTravelData.ProtoReflect.Descriptor instead.
func (*WestTravelData) Descriptor() ([]byte, []int) {
	return file_WestTravel_proto_rawDescGZIP(), []int{1}
}

func (x *WestTravelData) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *WestTravelData) GetBackgroundID() int32 {
	if x != nil && x.BackgroundID != nil {
		return *x.BackgroundID
	}
	return 0
}

func (x *WestTravelData) GetLevelType() int32 {
	if x != nil && x.LevelType != nil {
		return *x.LevelType
	}
	return 0
}

func (x *WestTravelData) GetUnlockTime() int64 {
	if x != nil && x.UnlockTime != nil {
		return *x.UnlockTime
	}
	return 0
}

type WestTravelDataMsgSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WestTravelDatas []*WestTravelData `protobuf:"bytes,1,rep,name=WestTravelDatas" json:"WestTravelDatas,omitempty"`
}

func (x *WestTravelDataMsgSync) Reset() {
	*x = WestTravelDataMsgSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WestTravel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WestTravelDataMsgSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WestTravelDataMsgSync) ProtoMessage() {}

func (x *WestTravelDataMsgSync) ProtoReflect() protoreflect.Message {
	mi := &file_WestTravel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WestTravelDataMsgSync.ProtoReflect.Descriptor instead.
func (*WestTravelDataMsgSync) Descriptor() ([]byte, []int) {
	return file_WestTravel_proto_rawDescGZIP(), []int{2}
}

func (x *WestTravelDataMsgSync) GetWestTravelDatas() []*WestTravelData {
	if x != nil {
		return x.WestTravelDatas
	}
	return nil
}

type WestTravelPassGameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId *int32 `protobuf:"varint,1,req,name=activityId" json:"activityId,omitempty"`
	LevelId    *int32 `protobuf:"varint,2,req,name=levelId" json:"levelId,omitempty"`
}

func (x *WestTravelPassGameReq) Reset() {
	*x = WestTravelPassGameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WestTravel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WestTravelPassGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WestTravelPassGameReq) ProtoMessage() {}

func (x *WestTravelPassGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_WestTravel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WestTravelPassGameReq.ProtoReflect.Descriptor instead.
func (*WestTravelPassGameReq) Descriptor() ([]byte, []int) {
	return file_WestTravel_proto_rawDescGZIP(), []int{3}
}

func (x *WestTravelPassGameReq) GetActivityId() int32 {
	if x != nil && x.ActivityId != nil {
		return *x.ActivityId
	}
	return 0
}

func (x *WestTravelPassGameReq) GetLevelId() int32 {
	if x != nil && x.LevelId != nil {
		return *x.LevelId
	}
	return 0
}

type WestTravelPassGameResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret *int32 `protobuf:"varint,1,req,name=ret" json:"ret,omitempty"`
}

func (x *WestTravelPassGameResp) Reset() {
	*x = WestTravelPassGameResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WestTravel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WestTravelPassGameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WestTravelPassGameResp) ProtoMessage() {}

func (x *WestTravelPassGameResp) ProtoReflect() protoreflect.Message {
	mi := &file_WestTravel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WestTravelPassGameResp.ProtoReflect.Descriptor instead.
func (*WestTravelPassGameResp) Descriptor() ([]byte, []int) {
	return file_WestTravel_proto_rawDescGZIP(), []int{4}
}

func (x *WestTravelPassGameResp) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

type WestTravelActivityPlayerDataSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SyncMsg *WestTravelActivityPlayerDataMsg `protobuf:"bytes,1,opt,name=syncMsg" json:"syncMsg,omitempty"`
}

func (x *WestTravelActivityPlayerDataSync) Reset() {
	*x = WestTravelActivityPlayerDataSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WestTravel_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WestTravelActivityPlayerDataSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WestTravelActivityPlayerDataSync) ProtoMessage() {}

func (x *WestTravelActivityPlayerDataSync) ProtoReflect() protoreflect.Message {
	mi := &file_WestTravel_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WestTravelActivityPlayerDataSync.ProtoReflect.Descriptor instead.
func (*WestTravelActivityPlayerDataSync) Descriptor() ([]byte, []int) {
	return file_WestTravel_proto_rawDescGZIP(), []int{5}
}

func (x *WestTravelActivityPlayerDataSync) GetSyncMsg() *WestTravelActivityPlayerDataMsg {
	if x != nil {
		return x.SyncMsg
	}
	return nil
}

var File_WestTravel_proto protoreflect.FileDescriptor

var file_WestTravel_proto_rawDesc = []byte{
	0x0a, 0x10, 0x57, 0x65, 0x73, 0x74, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43,
	0x69, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x22, 0x5d, 0x0a, 0x1f, 0x57, 0x65, 0x73, 0x74, 0x54, 0x72,
	0x61, 0x76, 0x65, 0x6c, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x73, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0a, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x78,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x61, 0x78,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x82, 0x01, 0x0a, 0x0e, 0x57, 0x65, 0x73, 0x74, 0x54, 0x72,
	0x61, 0x76, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x62, 0x61, 0x63, 0x6b,
	0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x44, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0c,
	0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x05, 0x52,
	0x09, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x6e,
	0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x02, 0x28, 0x03, 0x52, 0x0a,
	0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x65, 0x0a, 0x15, 0x57, 0x65,
	0x73, 0x74, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x73, 0x67, 0x53,
	0x79, 0x6e, 0x63, 0x12, 0x4c, 0x0a, 0x0f, 0x57, 0x65, 0x73, 0x74, 0x54, 0x72, 0x61, 0x76, 0x65,
	0x6c, 0x44, 0x61, 0x74, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d, 0x73,
	0x67, 0x2e, 0x57, 0x65, 0x73, 0x74, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x0f, 0x57, 0x65, 0x73, 0x74, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61,
	0x73, 0x22, 0x51, 0x0a, 0x15, 0x57, 0x65, 0x73, 0x74, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x50,
	0x61, 0x73, 0x73, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0a,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x07, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x49, 0x64, 0x22, 0x2a, 0x0a, 0x16, 0x57, 0x65, 0x73, 0x74, 0x54, 0x72, 0x61, 0x76,
	0x65, 0x6c, 0x50, 0x61, 0x73, 0x73, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74,
	0x22, 0x71, 0x0a, 0x20, 0x57, 0x65, 0x73, 0x74, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x53, 0x79, 0x6e, 0x63, 0x12, 0x4d, 0x0a, 0x07, 0x73, 0x79, 0x6e, 0x63, 0x4d, 0x73, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x2e, 0x57, 0x65, 0x73, 0x74, 0x54,
	0x72, 0x61, 0x76, 0x65, 0x6c, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x73, 0x67, 0x52, 0x07, 0x73, 0x79, 0x6e, 0x63,
	0x4d, 0x73, 0x67, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x69, 0x6d, 0x7a, 0x68, 0x6f, 0x6e, 0x67, 0x71, 0x69, 0x2f, 0x78, 0x64, 0x64, 0x71,
	0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62,
}

var (
	file_WestTravel_proto_rawDescOnce sync.Once
	file_WestTravel_proto_rawDescData = file_WestTravel_proto_rawDesc
)

func file_WestTravel_proto_rawDescGZIP() []byte {
	file_WestTravel_proto_rawDescOnce.Do(func() {
		file_WestTravel_proto_rawDescData = protoimpl.X.CompressGZIP(file_WestTravel_proto_rawDescData)
	})
	return file_WestTravel_proto_rawDescData
}

var file_WestTravel_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_WestTravel_proto_goTypes = []any{
	(*WestTravelActivityPlayerDataMsg)(nil),  // 0: com.yq.msg.CityMsg.WestTravelActivityPlayerDataMsg
	(*WestTravelData)(nil),                   // 1: com.yq.msg.CityMsg.WestTravelData
	(*WestTravelDataMsgSync)(nil),            // 2: com.yq.msg.CityMsg.WestTravelDataMsgSync
	(*WestTravelPassGameReq)(nil),            // 3: com.yq.msg.CityMsg.WestTravelPassGameReq
	(*WestTravelPassGameResp)(nil),           // 4: com.yq.msg.CityMsg.WestTravelPassGameResp
	(*WestTravelActivityPlayerDataSync)(nil), // 5: com.yq.msg.CityMsg.WestTravelActivityPlayerDataSync
}
var file_WestTravel_proto_depIdxs = []int32{
	1, // 0: com.yq.msg.CityMsg.WestTravelDataMsgSync.WestTravelDatas:type_name -> com.yq.msg.CityMsg.WestTravelData
	0, // 1: com.yq.msg.CityMsg.WestTravelActivityPlayerDataSync.syncMsg:type_name -> com.yq.msg.CityMsg.WestTravelActivityPlayerDataMsg
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_WestTravel_proto_init() }
func file_WestTravel_proto_init() {
	if File_WestTravel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_WestTravel_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*WestTravelActivityPlayerDataMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WestTravel_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*WestTravelData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WestTravel_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*WestTravelDataMsgSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WestTravel_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*WestTravelPassGameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WestTravel_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*WestTravelPassGameResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WestTravel_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*WestTravelActivityPlayerDataSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_WestTravel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_WestTravel_proto_goTypes,
		DependencyIndexes: file_WestTravel_proto_depIdxs,
		MessageInfos:      file_WestTravel_proto_msgTypes,
	}.Build()
	File_WestTravel_proto = out.File
	file_WestTravel_proto_rawDesc = nil
	file_WestTravel_proto_goTypes = nil
	file_WestTravel_proto_depIdxs = nil
}
