// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: YueBao.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngotHomePb int32

const (
	IngotHomePb_IngotHomePb_Enter            IngotHomePb = 217001
	IngotHomePb_IngotHomePb_Deposit          IngotHomePb = 217002
	IngotHomePb_IngotHomePb_Withdraw         IngotHomePb = 217003
	IngotHomePb_IngotHomePb_Sync_Player_Data IngotHomePb = 217004
)

// Enum value maps for IngotHomePb.
var (
	IngotHomePb_name = map[int32]string{
		217001: "IngotHomePb_Enter",
		217002: "IngotHomePb_Deposit",
		217003: "IngotHomePb_Withdraw",
		217004: "IngotHomePb_Sync_Player_Data",
	}
	IngotHomePb_value = map[string]int32{
		"IngotHomePb_Enter":            217001,
		"IngotHomePb_Deposit":          217002,
		"IngotHomePb_Withdraw":         217003,
		"IngotHomePb_Sync_Player_Data": 217004,
	}
)

func (x IngotHomePb) Enum() *IngotHomePb {
	p := new(IngotHomePb)
	*p = x
	return p
}

func (x IngotHomePb) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IngotHomePb) Descriptor() protoreflect.EnumDescriptor {
	return file_YueBao_proto_enumTypes[0].Descriptor()
}

func (IngotHomePb) Type() protoreflect.EnumType {
	return &file_YueBao_proto_enumTypes[0]
}

func (x IngotHomePb) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *IngotHomePb) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = IngotHomePb(num)
	return nil
}

// Deprecated: Use IngotHomePb.Descriptor instead.
func (IngotHomePb) EnumDescriptor() ([]byte, []int) {
	return file_YueBao_proto_rawDescGZIP(), []int{0}
}

type RechargeItemData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EndTime    *int64          `protobuf:"varint,1,opt,name=endTime" json:"endTime,omitempty"`
	Index      *int32          `protobuf:"varint,2,req,name=index" json:"index,omitempty"`
	DepositNum *int32          `protobuf:"varint,3,opt,name=depositNum" json:"depositNum,omitempty"`
	RecordList []*YueBaoRecord `protobuf:"bytes,4,rep,name=recordList" json:"recordList,omitempty"`
}

func (x *RechargeItemData) Reset() {
	*x = RechargeItemData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_YueBao_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RechargeItemData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeItemData) ProtoMessage() {}

func (x *RechargeItemData) ProtoReflect() protoreflect.Message {
	mi := &file_YueBao_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeItemData.ProtoReflect.Descriptor instead.
func (*RechargeItemData) Descriptor() ([]byte, []int) {
	return file_YueBao_proto_rawDescGZIP(), []int{0}
}

func (x *RechargeItemData) GetEndTime() int64 {
	if x != nil && x.EndTime != nil {
		return *x.EndTime
	}
	return 0
}

func (x *RechargeItemData) GetIndex() int32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *RechargeItemData) GetDepositNum() int32 {
	if x != nil && x.DepositNum != nil {
		return *x.DepositNum
	}
	return 0
}

func (x *RechargeItemData) GetRecordList() []*YueBaoRecord {
	if x != nil {
		return x.RecordList
	}
	return nil
}

// 进入请求
type YueBaoEnterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId *int32 `protobuf:"varint,1,req,name=activityId" json:"activityId,omitempty"`
}

func (x *YueBaoEnterReq) Reset() {
	*x = YueBaoEnterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_YueBao_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YueBaoEnterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YueBaoEnterReq) ProtoMessage() {}

func (x *YueBaoEnterReq) ProtoReflect() protoreflect.Message {
	mi := &file_YueBao_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YueBaoEnterReq.ProtoReflect.Descriptor instead.
func (*YueBaoEnterReq) Descriptor() ([]byte, []int) {
	return file_YueBao_proto_rawDescGZIP(), []int{1}
}

func (x *YueBaoEnterReq) GetActivityId() int32 {
	if x != nil && x.ActivityId != nil {
		return *x.ActivityId
	}
	return 0
}

type YueBaoEnterResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret        *int32            `protobuf:"varint,1,req,name=ret" json:"ret,omitempty"`
	PlayerData *RechargeItemData `protobuf:"bytes,2,opt,name=playerData" json:"playerData,omitempty"`
}

func (x *YueBaoEnterResp) Reset() {
	*x = YueBaoEnterResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_YueBao_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YueBaoEnterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YueBaoEnterResp) ProtoMessage() {}

func (x *YueBaoEnterResp) ProtoReflect() protoreflect.Message {
	mi := &file_YueBao_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YueBaoEnterResp.ProtoReflect.Descriptor instead.
func (*YueBaoEnterResp) Descriptor() ([]byte, []int) {
	return file_YueBao_proto_rawDescGZIP(), []int{2}
}

func (x *YueBaoEnterResp) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

func (x *YueBaoEnterResp) GetPlayerData() *RechargeItemData {
	if x != nil {
		return x.PlayerData
	}
	return nil
}

// 储蓄 217002
type YueBaoDepositReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId *int32 `protobuf:"varint,1,req,name=activityId" json:"activityId,omitempty"`
	Index      *int32 `protobuf:"varint,2,req,name=index" json:"index,omitempty"`
	DepositNum *int32 `protobuf:"varint,3,opt,name=depositNum" json:"depositNum,omitempty"`
}

func (x *YueBaoDepositReq) Reset() {
	*x = YueBaoDepositReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_YueBao_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YueBaoDepositReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YueBaoDepositReq) ProtoMessage() {}

func (x *YueBaoDepositReq) ProtoReflect() protoreflect.Message {
	mi := &file_YueBao_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YueBaoDepositReq.ProtoReflect.Descriptor instead.
func (*YueBaoDepositReq) Descriptor() ([]byte, []int) {
	return file_YueBao_proto_rawDescGZIP(), []int{3}
}

func (x *YueBaoDepositReq) GetActivityId() int32 {
	if x != nil && x.ActivityId != nil {
		return *x.ActivityId
	}
	return 0
}

func (x *YueBaoDepositReq) GetIndex() int32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *YueBaoDepositReq) GetDepositNum() int32 {
	if x != nil && x.DepositNum != nil {
		return *x.DepositNum
	}
	return 0
}

type YueBaoDepositResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret *int32 `protobuf:"varint,1,req,name=ret" json:"ret,omitempty"`
}

func (x *YueBaoDepositResp) Reset() {
	*x = YueBaoDepositResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_YueBao_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YueBaoDepositResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YueBaoDepositResp) ProtoMessage() {}

func (x *YueBaoDepositResp) ProtoReflect() protoreflect.Message {
	mi := &file_YueBao_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YueBaoDepositResp.ProtoReflect.Descriptor instead.
func (*YueBaoDepositResp) Descriptor() ([]byte, []int) {
	return file_YueBao_proto_rawDescGZIP(), []int{4}
}

func (x *YueBaoDepositResp) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

// 取款 217003
type YueBaoInteractReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId *int32 `protobuf:"varint,1,req,name=activityId" json:"activityId,omitempty"`
}

func (x *YueBaoInteractReq) Reset() {
	*x = YueBaoInteractReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_YueBao_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YueBaoInteractReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YueBaoInteractReq) ProtoMessage() {}

func (x *YueBaoInteractReq) ProtoReflect() protoreflect.Message {
	mi := &file_YueBao_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YueBaoInteractReq.ProtoReflect.Descriptor instead.
func (*YueBaoInteractReq) Descriptor() ([]byte, []int) {
	return file_YueBao_proto_rawDescGZIP(), []int{5}
}

func (x *YueBaoInteractReq) GetActivityId() int32 {
	if x != nil && x.ActivityId != nil {
		return *x.ActivityId
	}
	return 0
}

type YueBaoInteractResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret         *int32  `protobuf:"varint,1,req,name=ret" json:"ret,omitempty"`
	BaseIngot   *string `protobuf:"bytes,2,opt,name=baseIngot" json:"baseIngot,omitempty"`
	RewardIngot *string `protobuf:"bytes,3,opt,name=rewardIngot" json:"rewardIngot,omitempty"`
}

func (x *YueBaoInteractResp) Reset() {
	*x = YueBaoInteractResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_YueBao_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YueBaoInteractResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YueBaoInteractResp) ProtoMessage() {}

func (x *YueBaoInteractResp) ProtoReflect() protoreflect.Message {
	mi := &file_YueBao_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YueBaoInteractResp.ProtoReflect.Descriptor instead.
func (*YueBaoInteractResp) Descriptor() ([]byte, []int) {
	return file_YueBao_proto_rawDescGZIP(), []int{6}
}

func (x *YueBaoInteractResp) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

func (x *YueBaoInteractResp) GetBaseIngot() string {
	if x != nil && x.BaseIngot != nil {
		return *x.BaseIngot
	}
	return ""
}

func (x *YueBaoInteractResp) GetRewardIngot() string {
	if x != nil && x.RewardIngot != nil {
		return *x.RewardIngot
	}
	return ""
}

// 操作记录
type YueBaoRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time       *int64 `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	Type       *int32 `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	IngotCount *int64 `protobuf:"varint,3,opt,name=ingotCount" json:"ingotCount,omitempty"`
	Plan       *int32 `protobuf:"varint,4,opt,name=plan" json:"plan,omitempty"`
}

func (x *YueBaoRecord) Reset() {
	*x = YueBaoRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_YueBao_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YueBaoRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YueBaoRecord) ProtoMessage() {}

func (x *YueBaoRecord) ProtoReflect() protoreflect.Message {
	mi := &file_YueBao_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YueBaoRecord.ProtoReflect.Descriptor instead.
func (*YueBaoRecord) Descriptor() ([]byte, []int) {
	return file_YueBao_proto_rawDescGZIP(), []int{7}
}

func (x *YueBaoRecord) GetTime() int64 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

func (x *YueBaoRecord) GetType() int32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *YueBaoRecord) GetIngotCount() int64 {
	if x != nil && x.IngotCount != nil {
		return *x.IngotCount
	}
	return 0
}

func (x *YueBaoRecord) GetPlan() int32 {
	if x != nil && x.Plan != nil {
		return *x.Plan
	}
	return 0
}

var File_YueBao_proto protoreflect.FileDescriptor

var file_YueBao_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x59, 0x75, 0x65, 0x42, 0x61, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12,
	0x63, 0x6f, 0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d,
	0x73, 0x67, 0x22, 0xa4, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x49,
	0x74, 0x65, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05,
	0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x4e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x64, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x40, 0x0a, 0x0a, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67,
	0x2e, 0x59, 0x75, 0x65, 0x42, 0x61, 0x6f, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x0a, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x30, 0x0a, 0x0e, 0x59, 0x75, 0x65,
	0x42, 0x61, 0x6f, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52,
	0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x22, 0x69, 0x0a, 0x0f, 0x59,
	0x75, 0x65, 0x42, 0x61, 0x6f, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74,
	0x12, 0x44, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x79, 0x71, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x2e, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72,
	0x67, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x22, 0x68, 0x0a, 0x10, 0x59, 0x75, 0x65, 0x42, 0x61, 0x6f,
	0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0a,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x4e, 0x75, 0x6d, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x4e, 0x75, 0x6d,
	0x22, 0x25, 0x0a, 0x11, 0x59, 0x75, 0x65, 0x42, 0x61, 0x6f, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x22, 0x33, 0x0a, 0x11, 0x59, 0x75, 0x65, 0x42, 0x61,
	0x6f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05,
	0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x22, 0x66, 0x0a, 0x12,
	0x59, 0x75, 0x65, 0x42, 0x61, 0x6f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52,
	0x03, 0x72, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x67, 0x6f,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x67,
	0x6f, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x67, 0x6f,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x49,
	0x6e, 0x67, 0x6f, 0x74, 0x22, 0x6a, 0x0a, 0x0c, 0x59, 0x75, 0x65, 0x42, 0x61, 0x6f, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x69, 0x6e, 0x67, 0x6f, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x69, 0x6e, 0x67, 0x6f, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x6c, 0x61, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6c, 0x61, 0x6e,
	0x2a, 0x81, 0x01, 0x0a, 0x0b, 0x49, 0x6e, 0x67, 0x6f, 0x74, 0x48, 0x6f, 0x6d, 0x65, 0x50, 0x62,
	0x12, 0x17, 0x0a, 0x11, 0x49, 0x6e, 0x67, 0x6f, 0x74, 0x48, 0x6f, 0x6d, 0x65, 0x50, 0x62, 0x5f,
	0x45, 0x6e, 0x74, 0x65, 0x72, 0x10, 0xa9, 0x9f, 0x0d, 0x12, 0x19, 0x0a, 0x13, 0x49, 0x6e, 0x67,
	0x6f, 0x74, 0x48, 0x6f, 0x6d, 0x65, 0x50, 0x62, 0x5f, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x10, 0xaa, 0x9f, 0x0d, 0x12, 0x1a, 0x0a, 0x14, 0x49, 0x6e, 0x67, 0x6f, 0x74, 0x48, 0x6f, 0x6d,
	0x65, 0x50, 0x62, 0x5f, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x10, 0xab, 0x9f, 0x0d,
	0x12, 0x22, 0x0a, 0x1c, 0x49, 0x6e, 0x67, 0x6f, 0x74, 0x48, 0x6f, 0x6d, 0x65, 0x50, 0x62, 0x5f,
	0x53, 0x79, 0x6e, 0x63, 0x5f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x44, 0x61, 0x74, 0x61,
	0x10, 0xac, 0x9f, 0x0d, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x69, 0x6d, 0x7a, 0x68, 0x6f, 0x6e, 0x67, 0x71, 0x69, 0x2f, 0x78, 0x64, 0x64,
	0x71, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62,
}

var (
	file_YueBao_proto_rawDescOnce sync.Once
	file_YueBao_proto_rawDescData = file_YueBao_proto_rawDesc
)

func file_YueBao_proto_rawDescGZIP() []byte {
	file_YueBao_proto_rawDescOnce.Do(func() {
		file_YueBao_proto_rawDescData = protoimpl.X.CompressGZIP(file_YueBao_proto_rawDescData)
	})
	return file_YueBao_proto_rawDescData
}

var file_YueBao_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_YueBao_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_YueBao_proto_goTypes = []any{
	(IngotHomePb)(0),           // 0: com.yq.msg.CityMsg.IngotHomePb
	(*RechargeItemData)(nil),   // 1: com.yq.msg.CityMsg.RechargeItemData
	(*YueBaoEnterReq)(nil),     // 2: com.yq.msg.CityMsg.YueBaoEnterReq
	(*YueBaoEnterResp)(nil),    // 3: com.yq.msg.CityMsg.YueBaoEnterResp
	(*YueBaoDepositReq)(nil),   // 4: com.yq.msg.CityMsg.YueBaoDepositReq
	(*YueBaoDepositResp)(nil),  // 5: com.yq.msg.CityMsg.YueBaoDepositResp
	(*YueBaoInteractReq)(nil),  // 6: com.yq.msg.CityMsg.YueBaoInteractReq
	(*YueBaoInteractResp)(nil), // 7: com.yq.msg.CityMsg.YueBaoInteractResp
	(*YueBaoRecord)(nil),       // 8: com.yq.msg.CityMsg.YueBaoRecord
}
var file_YueBao_proto_depIdxs = []int32{
	8, // 0: com.yq.msg.CityMsg.RechargeItemData.recordList:type_name -> com.yq.msg.CityMsg.YueBaoRecord
	1, // 1: com.yq.msg.CityMsg.YueBaoEnterResp.playerData:type_name -> com.yq.msg.CityMsg.RechargeItemData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_YueBao_proto_init() }
func file_YueBao_proto_init() {
	if File_YueBao_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_YueBao_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RechargeItemData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_YueBao_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*YueBaoEnterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_YueBao_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*YueBaoEnterResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_YueBao_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*YueBaoDepositReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_YueBao_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*YueBaoDepositResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_YueBao_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*YueBaoInteractReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_YueBao_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*YueBaoInteractResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_YueBao_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*YueBaoRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_YueBao_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_YueBao_proto_goTypes,
		DependencyIndexes: file_YueBao_proto_depIdxs,
		EnumInfos:         file_YueBao_proto_enumTypes,
		MessageInfos:      file_YueBao_proto_msgTypes,
	}.Build()
	File_YueBao_proto = out.File
	file_YueBao_proto_rawDesc = nil
	file_YueBao_proto_goTypes = nil
	file_YueBao_proto_depIdxs = nil
}
